### ISSUE TITLE
Some questions about pysc2

### ISSUE THREAD

**Issue by amerinoo** [deepmind/pysc2#104]
Hello everyone, I'm a student trying to implement a SC2 bot using pysc2 but I would like to resolve some dubts before to start.

Q1: Where are the agents described in the paper? Can we found they to use as an example?
Q2: What kind of algorithms are used in the current agents implementations?
Q3: Are there any StarCraft II AI agent competitions? What are the rules to win?

Thank you.

**Comment by tewalds** [comment]
1. DeepMind's agents aren't open source. Various people active here have written and open sourced their agents.
2. OpenAI's dqn is a decent starting point, though there are likely open source a3c implementations as well.
3. It's worth following the reddit and facebook groups for more details. http://sc2ai.net/ is one tournament, though I don't know much about it.

**Comment by amerinoo** [comment]
OK,Thank you!
