### ISSUE TITLE
how to enable full game rendering

### ISSUE THREAD

**Issue by alfonsolink** [deepmind/pysc2#106]
question : I successfully installed pysc2 on linux ubuntu and I can render the gameplay with its 2d basic shapes and texts using pysc2.bin.agent. But I see many sample videos that have the full game rendering. can I do the same for ubuntu linux pysc2?

**Comment by islamelnabarawy** [comment]
I believe the full game UI is not available on Linux (yet?). The videos you are seeing are probably using Windows.

**Comment by ShadowDancer** [comment]
@islamelnabarawy Are there even plans to make it available on Linux?

**Comment by islamelnabarawy** [comment]
I'm not affiliated with Deepmind or Blizzard, so I'm afraid I don't know the answer to that question.

**Comment by ShadowDancer** [comment]
I think it's unlikely considering amount of work it requires.

**Comment by alfonsolink** [comment]
Full game rendering works on Windows like a charm

**Comment by ShadowDancer** [comment]
@alfonsolink 
And so does on mac :) That's because they're selling this game for quite a while. However game is not available on linux, and I doubt that it even has render that works or linux.

**Comment by KevinCalderone** [comment]
In the underlying protocol, we've stated we plan to add this but haven't given a timeline: https://github.com/Blizzard/s2client-proto/blob/master/docs/protocol.md#rendered

It will work on Windows/Mac/Linux.

**Comment by herodrigues** [comment]
@KevinCalderone so, there's no way of even having basic 2D rendering using the C++ API right now?

**Comment by tewalds** [comment]
No, there isn't yet, but it's one of the top priorities to get working and released. Note that this means there will be rgb observations similar to the feature layers. It doesn't mean having a full UI for playing the game the same as on Windows/Mac. 

All the current videos have been rendered from Windows/Mac.
