### ISSUE TITLE
How to disable the full game rendering in windows

### ISSUE THREAD

**Issue by ATigerWang** [deepmind/pysc2#108]
Hi, I want to know that if I can disable the full game rendering in wondows, because the  rendering takes up a lot of resources.  It seems that we should pass some parameters to SC2_x64.exe, so I wonder whether there is a parameter to disable it? :D

**Comment by KevinCalderone** [comment]
See answer here: https://github.com/deepmind/pysc2/issues/91

**Comment by ATigerWang** [comment]
Thanks.
