### ISSUE TITLE
CollectMineralShards crashes game client

### ISSUE THREAD

**Issue by ShadowDancer** [deepmind/pysc2#109]
Does anyone have similar problem? I have client 1.17, checked with minimaps version 1.2 and 1.0. Windows client works ok, however on Ubuntu 17.10 it crashes. All other minigames work like charm

**Comment by thebunni** [comment]
Seeing the same on py2.7 or 3.5 on ubuntu 16.04 with client 1.17

`Entering load game phase.
Launching next game.
Next launch phase started: 2
Next launch phase started: 3
Next launch phase started: 4
Next launch phase started: 5
Next launch phase started: 6
Next launch phase started: 7
Next launch phase started: 8
Game has started.
Sending ResponseJoinGame
Error signal: '11'
`

**Comment by ShadowDancer** [comment]
Any succes on other clients?

**Comment by BW0ng** [comment]
There was found to be an issue with the 3.17 patch (#53). A fix was supposed to be in the 3.18 release.

**Comment by KevinCalderone** [comment]
Sorry this is still impacting people since we haven't uploaded a new Linux build since 3.17. We will be uploading a new one along side our next patch a few weeks from now.
