### ISSUE TITLE
pydota2

### ISSUE THREAD

**Issue by Nostrademous** [deepmind/pysc2#111]
I apologize for creating an issue to communicate this but I did not find any emails associated with the creators/maintainers of pysc2 listed in the profiles here.

I started creating a Dota2 framework based on the pysc2 framework created here. The github repo can be found here: [pydota2](https://github.com/pydota2/pydota2)

There are many differences obviously because of the difference in exposed and available API as well as the protocols, but I am re-using certain pieces of the code. This is very early in development currently and not ready for people to start writing agents and RL/ML approaches currently as I'm still wrapping protocol implementations. I am reaching out in case anyone has any issue with partial code re-use I'm leveraging. The pydota2 repository is public and under the same LICENSE as pysc2.

Please let me know if you have any issues with my partial re-use of your work.

Kind Regards,

**Comment by tewalds** [comment]
Go for it. PySC2 is licensed under the Apache2 license which allows such work.
