### ISSUE TITLE
screen state inconsistent shape

### ISSUE THREAD

**Issue by jtatusko** [deepmind/pysc2#114]
```
class DoNothingAgent(base_agent.BaseAgent):
    def step(self, obs):
        from pysc2.lib import actions
        _NO_OP = actions.FUNCTIONS.no_op.id
        state = obs.observation['screen']
        assert state.shape[0] == 17
        return actions.FunctionCall(_NO_OP, [])
```
Assertion sometimes failing b/c sometimes state[0] == 13. This is happening on Mac version -- linux version seems to work fine for some reason. Maybe issue caused by automatic update? This wasn't happening last week.

**Comment by tewalds** [comment]
You've got two different versions of pysc2. Git pull on both to get them to match.
