### ISSUE TITLE
ValueError: Function 331/Move_screen is currently not available

### ISSUE THREAD

**Issue by joshjanes** [deepmind/pysc2#120]
Anyone know why this error keeps popping up for me? I've tried wrapping the code in multiple if statements, for example

           `new_action = [sc2_actions.FunctionCall(_MOVE_SCREEN, [_NOT_QUEUED, coord])]
            if (len(obs[0].observation["multi_select"]) >= 1):
                if _MOVE_SCREEN in obs[0].observation["available_actions"]:
                    obs = env.step(actions=new_action)
                else:
                    env.step(actions=[sc2_actions.FunctionCall(_NO_OP, [])])
            else:
                env.step(actions=[sc2_actions.FunctionCall(_NO_OP, [])])`

but to no avail. _MOVE_SCREEN is a part of available_actions, yet the code still crashes with the value error. 

Anyone know any checks I can put in place to circumvent this?

**Comment by tewalds** [comment]
That should work. Do you have a repro case that someone can try?
