### ISSUE TITLE
How to select one unit in pysc2

### ISSUE THREAD

**Issue by JanathonL** [deepmind/pysc2#121]
I want to select every single one unit in a group and give every one a different order. After searching online, I found that I could use the select_unit function to select only one unit, but my problem is that after I select_all, I do not know the binding between index and unit_tag. I can only find seven features about the selected unit, not including the tag. How can I select the unit with its specific tag?

**Comment by tewalds** [comment]
You don't. PySC2 is designed for creating agents that are similar to humans in that they take spatial inputs and act only a handful of times per second. If you want to control each unit individually you'll prefer using the raw api. Blizzard created a c++ api around that, and command center makes that even easier. Take a look at https://github.com/Blizzard/s2client-proto for more information.
