### ISSUE TITLE
Where can I find raw APIs including in the release?

### ISSUE THREAD

**Issue by reatank** [deepmind/pysc2#122]
It is mentioned in the paper that 

> Although we have not used the raw API for machine learning research, it is included as part of
the release in order to support other use cases (e.g. scripted agents and visualisation) which the
community may find useful.

So how can I call the raw APIs through this release?

**Comment by greentfrapp** [comment]
The API and documentation can be found here:
<https://github.com/Blizzard/s2client-proto>
<https://github.com/Blizzard/s2client-api>

**Comment by tewalds** [comment]
The raw api (list of units) is not exposed through the environment api, but is available from the protos. The renderer uses them, but they aren't available to the agents. You're welcome to use the pysc2 libraries to write a new environment that uses raw observations and actions, or you can use something like CommandCenter that is based around the raw api.
