### ISSUE TITLE
Replay_Action - Replays are invalid

### ISSUE THREAD

**Issue by Lukasas** [deepmind/pysc2#125]
Hello,
I'm just trying to sort replays packs from blizzard but i just got Replay is invalid in output from replay_action. How can i get this to work so I can extract actions from all replays ? Replays I'm trying to read are from sc2client github (official from blizzard)

**Comment by tewalds** [comment]
It's entirely possible a small subset of the replays they post are invalid. Also, you've got to make sure you're using the right version of the game since replays are version dependent.
