### ISSUE TITLE
controller(pysc2/lib/remote_controller.py) observed actions  missing target minimap information

### ISSUE THREAD

**Issue by amxineohp** [deepmind/pysc2#128]
Hi
I found this problem when parse function information from replays.
It will raise exception like:
`ValueError: Unknown ability_id:`
on linux just play a game:
`python -m pdb pysc2/bin/play.py --map Simple64`
select several scv in the UI, then target/attack the minimap,
it will send below action to sc2 server:

> (Pdb) action
action_feature_layer {
  unit_command {
    ability_id: 23
    target_minimap_coord {
      x: 44
      y: 23
    }
  }
}

but the observe() will miss minimap info:

> controller.observe().actions 
[action_raw {
  unit_command {
    ability_id: 23
    target_world_space_pos {
      x: 66.75
      y: 60.75
    }
    unit_tags: 4314890241
    unit_tags: 4315152385
    unit_tags: 4315938817
    unit_tags: 4316463105
    unit_tags: 4317249537
    unit_tags: 4317773825
  }
}
**action_feature_layer {
  unit_command {
    ability_id: 23
  }
}**
]

**Comment by tewalds** [comment]
Which version of SC2 is this?

**Comment by amxineohp** [comment]
Python 3.5.2
SC2.3.16.1.zip
I thought only version 3.16 work for the 3.16 replay pack, let me know if I am wrong.

BTW, a simple solution is:

> def world_to_minimap_pos(x, y, map_x, map_y, minimap_dim):
    ratio = minimap_dim/max(map_x, map_y)
    to_x = int(x * ratio)
    to_y = int((-y + map_y) * ratio)
    return to_x, to_y

def fill_minimap_coord(act, map_size, minimap_x):
    pos = act.action_raw.unit_command.target_world_space_pos
    action = sc_pb.Action()
    unit_command = action.action_feature_layer.unit_command
    unit_command.ability_id = act.action_feature_layer.unit_command.ability_id
    to_x, to_y = world_to_minimap_pos(pos.x, pos.y, map_size.x, map_size.y, minimap_x)
    unit_command.target_minimap_coord.x = to_x
    unit_command.target_minimap_coord.y = to_y
    return action
