### ISSUE TITLE
Feature maps extracted from replays have digits out of range

### ISSUE THREAD

**Issue by DengpanFu** [deepmind/pysc2#130]
I am trying to extract feature maps from replays to conduct supervise learning, in this procedure, i found some extracted features are out of range.
in pysc2/lib/features.py line154
```
SCREEN_FEATURES = ScreenFeatures(
    ...
    unit_type=(1850, FeatureType.CATEGORICAL, colors.unit_type, False),
    ...
)
```
which means **screen feature: unit_type** is categorical and bounded by 1850, so we should do data pre-processing as the paper [SC2LE](https://arxiv.org/abs/1708.04782) described in section 4.3:

> **Input pre-processing** All the baseline agents share the same pre-processing of input feature layers.
We **_embed all feature layers containing categorical values into a continuous space which is
equivalent to using a one-hot encoding in the channel dimension followed by a 1 x 1 convolution_**.
We also re-scale numerical features with a logarithmic transformation as some of them such as
hit-points or minerals might attain substantially high values

But after i extracted replay 

> 7c84df5f0454257f5ebd07cb60ab405fb4062f3df80ab3a16a3f68e2c78602b5.SC2Replay

I found the max value of this screen_feature/unit_type is 1879, which is larger than 1850
Also, another replay

> 39c23cd78c1ea5313f21bd2fba393733208bc7d97f046cb0c0da1f939b1733bc.SC2Replay

has a max value 1883 of screen_feature/unit_type
I didn't try all the replays, so i don't know how many replays have this phenomenon and what's the exactly max value of screen_feture/unit_type, i also wonder if this will be happen when we run an agent in a full game.
BTW, the replays are all downloaded from [replay files](https://github.com/Blizzard/s2client-proto#downloads)

I found that konwn uint types are defined in pysc2/lib/static_data.py, in which there are 200 types with the largest type id is 894. but according to its reference: https://github.com/Blizzard/s2client-api/blob/master/include/sc2api/sc2_typeenums.h, there are 210 types with the largest type id 1910, none of these numbers is 1850, so what does 1850 stand for? Could anybody explain this, or tell me what's the max type could be, Thanks @tewalds

**Comment by DengpanFu** [comment]
I found that konwn uint types are defined in pysc2/lib/static_data.py, in which there are 200 types with the largest type id is 894. But according to its reference: https://github.com/Blizzard/s2client-api/blob/master/include/sc2api/sc2_typeenums.h, there are 210 types with the largest type id 1910, none of these numbers is 1850, so what does 1850 stand for? Can any one explain this, or tell me what's the max type could be, Thanks @tewalds

**Comment by tewalds** [comment]
This is due to the 4.0 balance patch that added new units. It's fixed in the dev branch and will be pushed to master soonish.

**Comment by dai-dao** [comment]
Hi @DengpanFu , I'm trying to extract replay data as well for supervised learning. But I can't find any documentation or tutorials on how to do it. I tried running pysc2.bin.replays_action but it didn't give me anything useful. Could you please share how you did it?

Thank you so much.
