### ISSUE TITLE
Required support for 4.1.+ SC2 versions in platforms.py

### ISSUE THREAD

**Issue by robbernan** [deepmind/pysc2#131]
Versions that are newer than 3.19.0 are not supported for replays

**Comment by coolralf** [comment]
This file could help: https://github.com/Blizzard/s2client-proto/blob/master/buildinfo/versions.json

**Comment by BenjaminWinter** [comment]
This issue also applies to the 4.0.2 version, which is the newest available Linux build.
The file given above does not have an entry though for 4.0.2 and manually adding an entry to the VERSIONS variable in the platforms module of pysc2 results in an unspecified error within SC2

**Comment by tewalds** [comment]
This is fixed in the dev branch, and will be in the master branch and official release soon.

**Comment by jozhang97** [comment]
Would anyone happen to have the data version for 4.0.2 and binary version Base59877? This is the version I obtain from downloading the Linux package 4.0.2 at https://github.com/Blizzard/s2client-proto#downloads .
I'm looking at the fix on the dev branch and I see this: https://github.com/deepmind/pysc2/commit/fee7133a9abd8f1dfc90d5e7c2884cae04283eb7
which while has a lot of the new ones, doesn't have this one. I tried using the other one for 4.0.2, but it does not seem to work, unfortunately.

**Comment by mushroom1116** [comment]
In my case, i want to use version 4.0.2 so i replaced all folders in path StarCraftII manually, but i forgot the hidden file  `.build.info` and got this error. When i fixed it the error disappeared.

**Comment by jozhang97** [comment]
Ah one can get the right version by running the replay on the game client, which will download the appropriate version. Then one can use pysc2 to replay the game

**Comment by windowshopr** [comment]
I am new to this repo, and am currently running version 5.0.9 and get the error shown below:

![image](https://user-images.githubusercontent.com/40477419/159842599-b865ab33-02c3-4108-aafa-e2032bd0758f.png)

Using Windows 10, Python 3.10 (I believe, or 3.8+ anyway).

My VERSION's only go up to 4.10.1:

`'4.10.1': Version(game_version='4.10.1', build_version=75800, data_version='DDFFF9EC4A171459A4F371C6CC189554', binary=None)}`

Can I manually add my own version to this lib list somehow? Or is it more detailed than that?

![image](https://user-images.githubusercontent.com/40477419/159842817-8279c33a-85fc-44a0-828a-2ab55e4537fe.png)

I'd love to just be able to add a line to the bottom of this haha something like:

`Version("5.0.9", 87702, "I_DONT_KNOW_HOW_THIS_STRING_IS_GENERATED", None)`

Any ideas? Really hope this is still being maintained and can get some support on it! Super fun is yet to be had by me! haha thanks!
