### ISSUE TITLE
Question: Does pysc2 suport multi-agents (multi-units) controls in mini games?

### ISSUE THREAD

**Issue by tjuHaoXiaotian** [deepmind/pysc2#134]
For example, can I control each marine independently in mini game DefeatRoaches?

**Comment by nwayt001** [comment]
I'm pretty sure you can't do this do this in pysc2, but it's not really a limitation in pysc2 it's more of a limitation in the StarCraft II game itself. You can only make one action at a time, you can't make simultaneous actions so you wouldn't be able to independently control each marine in a multi-agent style.  

You could possibly hack your way around it and change the frame rate at which your agent interacts with the game to something that's super-human speed.  This would give the appearance of multiple agents controlling different units.

**Comment by simonmeister** [comment]
You can select individual units and issue move commands for the unit currently selected. Is this what you meant? See https://github.com/deepmind/pysc2/blob/master/pysc2/lib/actions.py#L238 .

**Comment by tjuHaoXiaotian** [comment]
Can I get the unique identifier for each unit ?

**Comment by tjuHaoXiaotian** [comment]
OK, no problem, I got the unique identifier for each unit.

**Comment by perib** [comment]
how did you get the unique identifier?

**Comment by tewalds** [comment]
The pysc2 environment is intended to be used using primarily spatial observations and roughly human like actions, so doesn't let you control individual units. The underlying starcraft2 api exposes a raw api that gives a list of units and allows controlling individual units by tag. Feel free to use the pysc2 libraries to do that, but you may be better off using Blizzard's c++ api or command center for that.
