### ISSUE TITLE
Which non-spatial observations are used in the A3C baseline?

### ISSUE THREAD

**Issue by simonmeister** [deepmind/pysc2#135]
Do you use all of the non-spatial observations available in the observation_spec [1] for your A3C agent? I specifically wonder about the cargo, multi select and build queue observations, as these seem to be quite high-dimensional, yielding a lot of input channels. It would thus be interesting to know which pre-processing you use for cargo, multi select and build queue, in case you use them.

[1] https://github.com/deepmind/pysc2/blob/master/pysc2/lib/features.py#L226

**Comment by OriolVinyals** [comment]
We do not use those. But we use all the feature layers from both screen and mini game, and also player:

      scalar_features = tf.cast(observation.player, tf.float32)
      scalar_features = tf.log(scalar_features + 1.)
