### ISSUE TITLE
Detecting Episode Resets of DeepMind Minigames in replay

### ISSUE THREAD

**Issue by BenjaminWinter** [deepmind/pysc2#138]
Is it possible to detect the episode resets done by the deepmind scenarios while viewing a replay in pysc2?
What ive tried so far:

- use the player_result property, but it is only filled at end of replay, although if replays are recorded with pysc2.bin.play pysc2 reacts to the player_result property accordingly
- Find the reset keyword in the chat property, but the property stays empty
- search for a score objective or objective in general, but couldn't find one

**Comment by tewalds** [comment]
Can you be more explicit what you mean? You may have better luck asking on the discord channel.
