### ISSUE TITLE
Question:  How can I match the raw data (got from the raw object observations) with the feature layers?

### ISSUE THREAD

**Issue by tjuHaoXiaotian** [deepmind/pysc2#142]
Hi,
How can I match the raw data (got from the raw object observations) with the feature layers?
For example, How can I convert the world_space_pos (x: 26.001220703125 y: 26.275634765625) to the feature_layer_pos (x: 0-84, y: 0-84)? 
Following is an example of the raw data i got.
```
[
  {
    display_type: Visible
    alliance: Self
    tag: 4303093761
    unit_type: 48
    owner: 1
    pos {
      x: 26.001220703125
      y: 26.275634765625
      z: 7.99609375
    }
    facing: 4.66746711730957
    radius: 0.375
    build_progress: 1.0
    cloak: NotCloaked
    is_selected: true
    is_on_screen: true
    is_blip: false
    health: 45.0
    health_max: 45.0
    shield: 0.0
    energy: 0.0
    is_flying: false
    is_burrowed: false
    orders {
      ability_id: 16
      target_world_space_pos {
        x: 25.428466796875
        y: 20.0
      }
    }
    assigned_harvesters: 0
    ideal_harvesters: 0
    weapon_cooldown: 0.0
    shield_max: 0.0
    energy_max: 0.0
  },
...,
]
```

**Comment by tewalds** [comment]
The transform is not exactly trivial. Take a look at lib/renderer_human.py or #141 for examples.

**Comment by tjuHaoXiaotian** [comment]
@tewalds Thanks, I got it.

**Comment by EveLIn3** [comment]
@tjuHaoXiaotian 
Hi, may I ask how did you extract those raw information? Can we do that using solely pysc2?
Thx

**Comment by tewalds** [comment]
Sure, pysc2 can be used for that as a library. The environment (sc2_env.SC2Env) doesn't expose the raw information, and likely never will beyond what's in #141.

**Comment by Saman-Naseri** [comment]
Hello, I was wondering if someone could tell me what the facing values mean? I think they mean what direction the unit is facing, but I don't know what directions the values represent.

**Comment by sflc6** [comment]
> Sure, pysc2 can be used for that as a library. The environment (sc2_env.SC2Env) doesn't expose the raw information, and likely never will beyond what's in #141.

Could you say how to use `pysc2` to extract the fine-grained raw information above? Right now, I'm only able to see numbers rounded to integers within the `sc2_env.SC2Env` object.
