### ISSUE TITLE
Flag error

### ISSUE THREAD

**Issue by keerthanpg** [deepmind/pysc2#146]
So, I declared a basic SC2 environment with a single line unit the init function of SC2Env class. However, it is giving me this error:

> Trying to access flag sc2_verbose before flags were parsed. This will raise an exception in the future.

Any idea how I should resolve this?

**Comment by tewalds** [comment]
I'd suggest using absl.app to run your program. That will do the flag parsing needed. Alternatively you can do that yourself with absl.flags.

**Comment by keerthanpg** [comment]
Resolved this by manually parsing the flags before using them.
