### ISSUE TITLE
Distinguishing Beacons

### ISSUE THREAD

**Issue by ritzbd** [deepmind/pysc2#147]
I'm relatively new to this toolkit, so (please) forgive and correct me if I'm incorrect here.

As I understand it, we can determine if a location in the observation is a beacon by recognizing it as a PLAYER_NEUTRAL. I'm wondering if there's any method for distinguishing one beacon from another (ie Beacon0, Beacon1, etc) with coordinate locations tied to, for example, their centers.

I want this functionality essentially to make it easier to queue specific paths between locations. Without this, I'm forced to determine [x,y] coordinates for each step along the path (manually). If I could extract beacon locations from a list of them, I could path from Beacon0 to Beacon3 to Beacon5. Then, if the beacons ever move, my agent still can find the path without manual update.

I think this may be outside the realm of what pysc2 is designed for, but if it's there, knowing would be great. Any help is greatly appreciated.

**Comment by skjb** [comment]
Maybe my latest article will help: https://medium.com/@skjb/how-to-locate-and-select-units-in-pysc2-2bb1c81f2ad3

**Comment by ritzbd** [comment]
That was fairly informative, yes. It doesn't quite meet all of my goals, but that's okay - I think I have figured out a different way to handle things. It's tedious, but tedium isn't always bad.
