### ISSUE TITLE
Replays for SC2 4.1.4

### ISSUE THREAD

**Issue by raymondchua** [deepmind/pysc2#148]
Hi, 
It seems that the replays provided here are for SC2 3.16. Is there a way we can use these replays for SC2 4.14? If not, does anyone knows how I can get a copy of SC2 3.16?

**Comment by H-Park** [comment]
This is pretty hidden, but is exactly what you are looking for: https://github.com/Blizzard/s2client-proto/tree/33f0ecf615aa06ca845ffe4739ef3133f37265a9/samples/replay-api

You need to create an API account on the blizzard website, and once you do that, this will pull every replay pack matching the specified sc2 client version. For 4.0.2 I got a little over 139,000 replays!
