### ISSUE TITLE
CollectMineralShardsFeatureUnits scripted agent does not select units fairly.

### ISSUE THREAD

**Issue by now-raymond** [deepmind/pysc2#153]
Thanks for the wonderful framework!

It seemed strange to me that the `CollectMineralShardsFeatureUnits` agent was achieving lower scores (~75) than `CollectMineralShards` (~90) even though it was written to control two units independently rather than as a group and thus could theoretically cover more ground in the same time.

It appears that `CollectMineralShardsFeatureUnits` does not select and issue move commands to units fairly, often resulting in the agent getting stuck alternately selecting units without performing any move action at all, or a single unit making multiple movement actions while the other unit sits idle.

This issue seems to stem from the order of units in `obs.observation.feature_units` being indeterminate across timesteps. In the [current code](https://github.com/deepmind/pysc2/blob/161dfa6ad5db097d42d024afbaf03657e431eb44/pysc2/agents/scripted_agent.py#L99), the index of the current marine within this list is stored and alternated between 0 and 1. The order of the list can change across timesteps, so a stored list index cannot be used to reliably refer to the same unit in a different timestep.

Here's a quick capture of the issue:
![collect_mineral_shards_feature_units](https://user-images.githubusercontent.com/11659716/37571912-3ab19bcc-2afb-11e8-9638-05622eb5d3de.gif)

**Comment by now-raymond** [comment]
I've submitted a PR (#154) with my proposed changes to fix this issue.

**Comment by tewalds** [comment]
Thanks for the PR! Merged.
