### ISSUE TITLE
Map class description not clear enough

### ISSUE THREAD

**Issue by swissman777** [deepmind/pysc2#156]
Hello; I am trying to do make a custom map acceptable for scripted agents. The thing is I am new at this and the comment of the Map class is not very clear to me. Is anyone willing to help?

This is the full comment of the map class at pysc2/maps/lib.py  : 

"""The library and base Map for defining full maps.

To define your own map just import this library and subclass Map. It will be
automatically registered for creation by `get`.

  class NewMap(lib.Map):
    prefix = "map_dir"
    filename = "map_name"
    players = 3

You can build a hierarchy of classes to make your definitions less verbose.

To use a map, either import the map module and instantiate the map directly, or
import the maps lib and use `get`. Using `get` from this lib will work, but only
if you've imported the map module somewhere.
"""

**Comment by tewalds** [comment]
What are you trying to do?

To add your own, put the map file in the maps directory, then also add a subclass of lib.Map somewhere with prefix and filename pointing to the right place. Then launch the game with that map name. Feel free to send a pull request with clearer documentation.

**Comment by swissman777** [comment]
Well, is it possible to get an example? I read the documentation and it's not very clear. Also how do you send a pull request for clearer doc?

**Comment by tewalds** [comment]
Is that NewMap not an example? 

Github has a lot of documentation on how to generate pull requests: https://help.github.com/ . In general:
- fork pysc2 to your own repo
- git clone your repo
- make some changes
- commit
- push to github
- go to your repo and click create pull-request.
