### ISSUE TITLE
Can't get pysc2 to work on windows 8

### ISSUE THREAD

**Issue by ad591964** [deepmind/pysc2#159]
I get the following error when I try to run the command "python -m pysc2.bin.play --map Simple64" 

I0329 18:02:50.506149  2420 sc_process.py:148] Connection attempt 0 (running: None)
I0329 18:02:51.510105  2420 sc_process.py:148] Connection attempt 1 (running: None)
I0329 18:02:52.511059  2420 sc_process.py:148] Connection attempt 2 (running: None)
I0329 18:02:53.512022  2420 sc_process.py:148] Connection attempt 3 (running: None)
I0329 18:02:54.512966  2420 sc_process.py:148] Connection attempt 4 (running: None)
I0329 18:02:55.513924  2420 sc_process.py:148] Connection attempt 5 (running: None)
I0329 18:02:56.514617  2420 sc_process.py:148] Connection attempt 6 (running: None)
I0329 18:02:57.515570  2420 sc_process.py:148] Connection attempt 7 (running: None)
I0329 18:02:58.516514  2420 sc_process.py:148] Connection attempt 8 (running: None)
I0329 18:02:59.517467  2420 sc_process.py:148] Connection attempt 9 (running: None)
I0329 18:03:00.518383  2420 sc_process.py:148] Connection attempt 10 (running: None)
I0329 18:03:01.519334  2420 sc_process.py:148] Connection attempt 11 (running: None)
I0329 18:03:02.519404  2420 sc_process.py:148] Connection attempt 12 (running: None)
I0329 18:03:03.520033  2420 sc_process.py:148] Connection attempt 13 (running: None)
I0329 18:03:04.520188  2420 sc_process.py:148] Connection attempt 14 (running: None)
I0329 18:03:05.520395  2420 sc_process.py:148] Connection attempt 15 (running: None)
I0329 18:03:06.520936  2420 sc_process.py:148] Connection attempt 16 (running: None)
I0329 18:03:07.521367  2420 sc_process.py:148] Connection attempt 17 (running: None)
I0329 18:03:08.522074  2420 sc_process.py:148] Connection attempt 18 (running: None)
I0329 18:03:09.522715  2420 sc_process.py:148] Connection attempt 19 (running: None)
I0329 18:03:10.522857  2420 sc_process.py:148] Connection attempt 20 (running: None)
I0329 18:03:11.523796  2420 sc_process.py:148] Connection attempt 21 (running: None)
I0329 18:03:12.523866  2420 sc_process.py:148] Connection attempt 22 (running: None)
I0329 18:03:13.524719  2420 sc_process.py:148] Connection attempt 23 (running: None)
I0329 18:03:14.524737  2420 sc_process.py:148] Connection attempt 24 (running: None)
I0329 18:03:15.524966  2420 sc_process.py:148] Connection attempt 25 (running: None)
I0329 18:03:16.525624  2420 sc_process.py:148] Connection attempt 26 (running: None)
I0329 18:03:17.525947  2420 sc_process.py:148] Connection attempt 27 (running: None)
I0329 18:03:18.525998  2420 sc_process.py:148] Connection attempt 28 (running: None)
I0329 18:03:19.526328  2420 sc_process.py:148] Connection attempt 29 (running: None)
W0329 18:03:20.526573  2420 sc_process.py:146] SC2 isn't running, so bailing early on the websocket connection.
W0329 18:03:23.638236  2420 sc_process.py:183] Killing the process.
I0329 18:03:23.709288  2420 sc_process.py:166] Shutdown with return code: 1
Failed to create the socket.

SC2 opens to a black screen and close soon after. I am not sure why it does not work. Any ideas?

**Comment by twang4446** [comment]
I meet exactly the same problem....

**Comment by lfricken** [comment]
Have you made sure sc2 works by itself?

**Comment by ad591964** [comment]
@lfricken SC2 works fine when I play it normally.

**Comment by twang4446** [comment]
@lfricken  Yes, I can play SC2 normally by itself, but the problem occurs when start from pysc2.

**Comment by tewalds** [comment]
Try adding logging: --logtostderr . Maybe that'll give you an idea of what's wrong.

**Comment by cosmoni** [comment]
any update on this? im having the exact same thing after the most recent update. it was working fine before and now just a black screen. i tried adding logging but it didn't seem to do anything, where is it supposed to be putting the log?

**Comment by cosmoni** [comment]
in my case it turned out to be my python version/firewall. i was running 3.6 but then created a new environment for 3.5 and when i tried to run it from there i suddenly got a bunch of firewall warnings which i allowed and then the game ran fine. so im not sure if it was actually the version or if those firewall warnings just weren't coming up before for some reason.
