### ISSUE TITLE
Max Episode Flag

### ISSUE THREAD

**Issue by MichaelStuartJr** [deepmind/pysc2#160]
So, I'm currently running side-by-side tests to see which yields better results. I think having a max episode flag would be beneficial to see, for example, which set of rules collects more mineral shards over 100 games. This may already exist and just haven't found it. 😞 If this isn't already available, I have some code stubbed out to accomplish this. If someone could point me in the right direction or tell me to create a PR that would be great! 😄 

Thanks!

**Comment by tewalds** [comment]
max_agent_steps: https://github.com/deepmind/pysc2/blob/master/pysc2/bin/agent.py#L43 will get you most of the way there. A pull request might be accepted.

**Comment by tewalds** [comment]
Pull request accepted in 5c1969f
