### ISSUE TITLE
Question: pysc2.lib.protocol.ProtocolError

### ISSUE THREAD

**Issue by voiler** [deepmind/pysc2#162]
when the env run only 1 episode, it raise an error.
pysc2/lib/protocol.py line 99, in read
pysc2.lib.protocol.ProtocolError: Error in RPC response (likely a bug). Prev status: Status.in_game, new status: Status.ended, error:
Game has already ended

how can i solve it?
Thanks

**Comment by tewalds** [comment]
Does this always happen? Is it limited to a single map? Which version are you running? Essentially, how can I reproduce this?

**Comment by voiler** [comment]
First of all, my English is not very good, some statements may not be very clear. I’m sorry to have caused you some trouble.

1> It always happens.
2> But the error only raise when I used the mini-game map-"FindAndDefeatZerglings". The other mini-map doesn't raise error.  
3> I run it on Windows 10. The sc2 is latest. but when I run it on Ubuntu, the error doesn't appear.
I want to get the original game image to make some gif images as a result, so it must run on Windows.
4> My python environment is anaconda with python 3.5.  
I install the packages  by command `conda install futures`  and `pip install pysc2 tensorflow cloudpickle` 
then i run code from  [https://github.com/pekaalto/sc2aibot](url).

First, it raise `AttributeError: module 'absl.logging' has no attribute 'critical'`   in pysc2/lib/protocol.py line 98, but I can't found the 'critical' in absl.logging, then I comment out this line.
Run it again, it raise the error I asked in my question . 

thanks.

**Comment by tewalds** [comment]
This is fixed in 4.1.2 that should be released by blizzard in the next couple days, and is mentioned in the discord channel.
