### ISSUE TITLE
data regarding non-valid actions due to non-valid arguments

### ISSUE THREAD

**Issue by natangold85** [deepmind/pysc2#163]
hello.
there are actions which are presence in the "available_actions" but are not valid due to not-valid arguments. for example, action to build a building is not valid if the screen location given in arguments is not valid (due to the height map or other reason).

in this case in the graphical environment of the game there is a a red line that saying that the location chosen for building is not valid. there is a way i can understand this output from the observation given in the step function? if not, there is another way to retrieve this data? so far i only succeed to retrieve this data through the screen observation but it retrieved in delay of a few steps (that is caused by the time that is taking to the scv to reach the building coordinate)
maybe there is a way to get from the screen observation the green mark that appear before the scv reach the building coordinate?

thanks
natan

**Comment by tewalds** [comment]
Unfortunately we didn't try to model whether a location is buildable or not. It's not quite clear how we'd do that. Smart agents can figure that out over time though, in the same way that you can predict pretty accurately whether a location is buildable. The observation of last_actions (in the dev branch) lets you figure out if it was successful, and try again.
