### ISSUE TITLE
about create a new minigame map by self

### ISSUE THREAD

**Issue by PeterLayton** [deepmind/pysc2#166]
**How to create a new minigame map by self?**
**correctly, I want to know the minigame map script frame**
**could you create a document to describe the minigame map script frame?**

**Comment by chris-chris** [comment]
@tewalds Can I try this? 
I can write a tutorial for minigame map generation.

**Comment by SoyGema** [comment]
Hi There,


@PeterLayton Hi there. 👍 Thanks for your interest towards creating new mini games .
- You can pass by this [markdown ](https://github.com/SoyGema/Startcraft_pysc2_minigames/blob/master/docs/README.md) I've created  but is quite far from being straightforward and not very readable. :( 
-  Please read this [issue](https://github.com/SoyGema/Startcraft_pysc2_minigames/issues/4) and check that your version of SC2 doesn't hold dependencies or license issues ^^ . 
- I am supporting my learning about the editor in this [page ](https://sc2mapster.gamepedia.com/SC2Mapster_Wiki)


@chris-chris please let me know if I can help you towards that tutorial -maybe taking the useful parts of the markdown and producing some more material and publishing in your blog?- , in the FAQs I've received towards mini-games the community seems to be more interested in editing the existing ones to create a Defeat'Whatever' melee as an start for it . 💯 

@tewalds many thanks for the ping! ^^

**Comment by PeterLayton** [comment]
@SoyGema Thanks for your great help! This very useful. like it so much!
