### ISSUE TITLE
SC2_x64.exe - Application Error - memory address

### ISSUE THREAD

**Issue by ericvoots** [deepmind/pysc2#169]
I am getting the following error when running:

python -m pysc2.bin.agent --map Simple64

![pysc2_error](https://user-images.githubusercontent.com/15186821/39658924-5a73dafa-4feb-11e8-8a2a-b4dee954e47a.png)

**Comment by ericvoots** [comment]
I am running version 4.30.  Regular play of the game works fine.

**Comment by tewalds** [comment]
Maybe ask on the discord channel? http://wiki.sc2ai.net/Main_Page
