### ISSUE TITLE
modified map not open properly on linux

### ISSUE THREAD

**Issue by natangold85** [deepmind/pysc2#175]
hey, i changed one of the mini games maps through star craft map editor and run an agent in windows. everything worked properly. now when i try to run this agent with the same map on linux the map loaded is an empty map. do you have any idea why it is happening?

**Comment by tewalds** [comment]
The editor probably wrote it in a format that doesn't work with old versions of the game. I'm not sure if there's a way to specify that you want it to work in an old version, otherwise you'll either need to find an old editor and redo it, or wait for a newer linux version.
