### ISSUE TITLE
Errors reported when running in multiplayer mode

### ISSUE THREAD

**Issue by pkuso** [deepmind/pysc2#177]
According to the restart mechanism used for Multiplayer mode (i.e., leave, create and join), we can restart the game in linux. However, we found the following error when the games are played around 10,000 episodes.

> Game has started.
Sending ResponseJoinGame
I0516 19:37:22.379059 140327922956032 new_environment.py:182] Starting episode: 1010
FILE OPEN ERROR: for /tmp/sc-friic4hx/SC2/ProgramData/Blizzard/StarCraft II/2018-05-16 19T37T24.4584.test: Too many open files
FILE OPEN ERROR: for /home/ubuntu/env/game/StarCraftII/AppData/2018-05-16 19T37T24.4624.test: Too many open files

Any suggestions?

**Comment by tewalds** [comment]
I wonder if this is related: https://github.com/Blizzard/s2client-proto/issues/102
