### ISSUE TITLE
Suggestion to add absolute imports to play_vs_agent.py

### ISSUE THREAD

**Issue by NikEyX** [deepmind/pysc2#181]
Hi Timo,

please consider adding the below code so that people can launch their bots from absolute paths. This becomes especially relevant for the laddermanager.

```
def agent():
  """Run the agent, connecting to a (remote) host started independently."""
  agent_module, agent_name = FLAGS.agent.rsplit(".", 1)

  #don't forget to import os
  if os.path.isabs(agent_module):
    dirname = os.path.dirname(agent_module)
    import sys
    sys.path.append(dirname)
    os.chdir(dirname)

    logging.info('Changed working directory to: %s' % dirname)
    agent_cls = getattr(importlib.import_module(os.path.basename(agent_module)), agent_name)
  else:
    logging.info('Loading agent using relative path: %s' % agent_module)
    agent_cls = getattr(importlib.import_module(agent_module), agent_name)
```

**Comment by tewalds** [comment]
Can you give an example usage of this?

**Comment by NikEyX** [comment]
It appears there is another way to run it on the ladder manager. Thanks though.

**Comment by Archiatrus** [comment]
I think adding those lines is a good idea. An example call could then be

```python -m pysc2.bin.play_vs_agent --agent C:/Ladder/Bots/SimpleAgent/simple_agent.SimpleAgent --host_port 5678 --lan_port 5692 --map Interloper --agent_race terran```

The person running the ladder manager can have pysc2 installed while the files for the bot don't need to be on the python path.
