### ISSUE TITLE
Spatial mismatch between minimap and screen clicking locations

### ISSUE THREAD

**Issue by ConstantinosM** [deepmind/pysc2#185]
My agent is trained to get to a location (3,19) by using two actions:

Smart_minimap action (id=452) and Attack_screen action (id=12)

It is trained to avoid a specific location (distractor) and thus it uses two clicks, so it does not use a straight path to the target.

The first click with Smart_minimap action is at location (3,19) according to the output of the network (just printing the selected click location of the Smart_minimap action). The game screen and pygame screen though show that the agent is clicking on a different location.

When the agent has passed the distractor's location it uses the Attack_screen action to click on (3,19). In this case the network's output, screen location in pygame and in  the game  match (and the agent reaches the target).

I did a bit of investigation and checked the code through debugging and I noticed that in the sc2_env.py in the step function, self._obs have a C-style function call. In the above scenario I get:

<class 'list'>: [actions {
  action_raw {
    unit_command {
      ability_id: 1
      target_world_space_pos {
        x: 22.0
        y: 25.0
      }
      unit_tags: 4298899457
    }
  }
  action_feature_layer {
    unit_command {
      ability_id: 1
      target_screen_coord {
        x: 1
        y: 16
      }
    }

The action (1,16) is the action that I observe on the game screen (and the pygame screen) while the agent is doing Smart_minimap on (3,19). When my agent eventually uses the Attack_screen action clicking at the (3,19), in the game (and the pygame screen), by looking at the self._obs I get:

<class 'list'>: [actions {
  action_raw {
    unit_command {
      ability_id: 23
      target_world_space_pos {
        x: 23.625
        y: 22.375
      }
      unit_tags: 4298899457
    }
  }
  action_feature_layer {
    unit_command {
      ability_id: 23
      target_screen_coord {
        x: 3
        y: 19
      }
    }

Which is the correct action that I observe. 
My question:
It seems that the click location of a minimap action is different from a screen action. What is the transformation for mapping minimap actions to screen actions?
Any help would be great!

**Comment by tewalds** [comment]
I'm not sure I understand the question entirely. If you're playing through the pygame screen, location should be correct if you're playing through the same api (ie rendered vs feature layer), but not quite the same otherwise. I don't have the correct camera transforms between rendered and feature layers. So, if you click on the right side, it should be right.

**Comment by tewalds** [comment]
Most of https://github.com/deepmind/pysc2/blob/master/pysc2/lib/renderer_human.py#L363 is dedicated to the transforms between world and screen/minimap, but I'm not sure that's what you're looking for. This may be easier to resolve on discord: https://discord.gg/qTZ65sh
