### ISSUE TITLE
Error while running scripted agents

### ISSUE THREAD

**Issue by sumitsk** [deepmind/pysc2#189]
Running scipted agents in the latest cloned version of the repository throws an error. Specifically, the command `python -m pysc2.bin.agent --map MoveToBeacon` throws this `ValueError: Map only supports 1 player, but trying to join with 2`. How can I fix this? 

Moreover, This error is not experienced if I use the pip version of the repository.

**Comment by tewalds** [comment]
This should be fixed in ffe3823.
