### ISSUE TITLE
pysc2.bin.replay_actions : parsing valid replays as invalid.

### ISSUE THREAD

**Issue by Elirso** [deepmind/pysc2#19]
Hello, I'm still trying to make replay_actions work.

I've run across another bug : when I launch it with replay as arguments : `python -m pysc2.bin.replay_actions --replays "D:\Program Files\StarCraft II\Replays\test"`, it first says 2 replay found (normal), but later in the execution, the replays are found to be invalid. 

It might have something to do with the fact that there is a point from where the replay is referenced as "replay.SC2Repla", and nor "replay.SC2Replay" (the 'y' is missing).

Here is the file of the output I get : see the difference between line 40 and 41 , the 'y' disappeard, and the replay is invalid.
[dump.txt](https://github.com/deepmind/pysc2/files/1217965/dump.txt)

**Comment by tewalds** [comment]
Is that replay played on ladder? The map name looks bizarre so probably is corrupt.

**Comment by Elirso** [comment]
The map name contains an accent ('é'), because that's the french name of the map. it is a ladder game, played past 3.16.1

**Comment by tewalds** [comment]
Can you upload the replay and map somewhere?
