### ISSUE TITLE
Place building actions can lead to illegal game states

### ISSUE THREAD

**Issue by dorthrithil** [deepmind/pysc2#193]
Using pysc2 build actions you can place buildings in such a way, that they actually overlap: 

<img width="1064" alt="screen shot 2018-06-06 at 19 27 03" src="https://user-images.githubusercontent.com/3655915/41055160-c8b07d4a-69c0-11e8-9d3a-ece870b0060e.png">

In the real game, such a placement is not possible and would lead to the screen alert: `Can't build, location invalid`.

The worker will in such a case be sent to the build location and then do nothing. So the building is not actually built on an invalid location. The agent however has a disadvantage to human players as it tries to perform invalid actions.

**Comment by tewalds** [comment]
This is definitely a bug for Blizzard.

**Comment by dorthrithil** [comment]
@tewalds Is https://github.com/Blizzard/s2client-proto the correct repo to report this?

**Comment by tewalds** [comment]
Yeah, that's the right place.
