### ISSUE TITLE
Blank rgb_screen, render_test fails

### ISSUE THREAD

**Issue by ConstantinosM** [deepmind/pysc2#194]
Running the render_test.py i get the following error:

Traceback (most recent call last):
  File "render_test.py", line 89, in test_render
    self.assertTrue(rgb_screen.any())
AssertionError: False is not true

I had noticed that also the rgb_screen/minimap are empty. I am on Mac and the previous version was working without a problem. Any help on what is happening with the pixel observations?

**Comment by ConstantinosM** [comment]
I have managed to get pixel observations only in Linux so I stick with Linux for the moment. I couldn't manage to make it work in Mac. I debugged till the point when you receive the obs from the controller and are returned empty.

**Comment by gjcamacho** [comment]
Hello,

I am having the same issue. Not only on the test, but on any way pysc2 is run on mac. rgb_screen is filled with zeros. Any reason why this happens?
