### ISSUE TITLE
3.16 and 3.17 replays don't work

### ISSUE THREAD

**Issue by MichalOp** [deepmind/pysc2#197]
I can't play replays from SC2 versions 3.16 and 3.17 with pysc2.bin.play. I am using python 3.6.1, pysc2 2.0.1 on Windows. I played all replays manually in game to download older client versions and they worked fine.

Relplays from various 4.x versions work fine when played by pysc2, but when I attempt to play one of  3.16 or 3.17 replays it displays replay's info normally, launches SC2 and closes it almost immediately with the following error:

> E0619 16:22:04.923007  2652 _logging.py:54] close status: 16896
> I0619 16:22:05.525105  2652 sc_process.py:197] Shutdown gracefully.
> I0619 16:22:05.525105  2652 sc_process.py:182] Shutdown with return code: 0
> Traceback (most recent call last):
>   File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "C:\Users\Michal\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\Michal\AppData\Local\Programs\Python\Python36\lib\site-packages\pysc2\bin\play.py", line 212, in <module>
>     app.run(main)
>   File "C:\Users\Michal\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\app.py", line 274, in run
>     _run_main(main, args)
>   File "C:\Users\Michal\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\app.py", line 238, in _run_main
>     sys.exit(main(argv))
>   File "C:\Users\Michal\AppData\Local\Programs\Python\Python36\lib\site-packages\pysc2\bin\play.py", line 157, in main
>     controller.start_replay(start_replay)
>   File "C:\Users\Michal\AppData\Local\Programs\Python\Python36\lib\site-packages\pysc2\lib\remote_controller.py", line 88, in _valid_status
>     return func(self, *args, **kwargs)
>   File "C:\Users\Michal\AppData\Local\Programs\Python\Python36\lib\site-packages\pysc2\lib\remote_controller.py", line 63, in _check_error
>     return check_error(func(*args, **kwargs), error_enum)
>   File "C:\Users\Michal\AppData\Local\Programs\Python\Python36\lib\site-packages\pysc2\lib\remote_controller.py", line 54, in check_error
>     raise RequestError("%s.%s: '%s'" % (enum_name, error_name, details), res)
> pysc2.lib.remote_controller.RequestError: SC2APIProtocol.ResponseStartReplay.Error.MissingOptions: ''

**Comment by dulex123** [comment]
Have the same problem on Ubuntu 16.04

**Comment by tewalds** [comment]
That's not a very helpful error message... Unfortunately I'm not sure what's wrong either. I'd recommend getting newer replays using https://github.com/Blizzard/s2client-proto/tree/master/samples/replay-api and stop using 3.16/3.17.

**Comment by rohanpaleja27** [comment]
Anyone find a fix to this? I am using the newest replays off the Blizzard github.

**Comment by nathanbwoods** [comment]
Experienced this issue using the 3.16.1 replays, moved up to 4.10.1 and it was solved. Give the new replays a try if you haven't.
