### ISSUE TITLE
'SDL.h' file not found on Mac

### ISSUE THREAD

**Issue by xwzy** [deepmind/pysc2#20]
python anaconda 3.5
mac os 10.12.5
 When install pysc2 by `pip install pysc2`, get this error.
```
    running build_ext
    building 'pygame.scrap' extension
    creating build/temp.macosx-10.6-x86_64-3.5
    creating build/temp.macosx-10.6-x86_64-3.5/src
    /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/wzy/anaconda/include -arch x86_64 -DENABLE_NEWBUF=1 -I/NEED_INC_PATH_FIX -I/Users/wzy/anaconda/include/python3.5m -c src/scrap.c -o build/temp.macosx-10.6-x86_64-3.5/src/scrap.o
    src/scrap.c:27:10: fatal error: 'SDL.h' file not found
    #include "SDL.h"
             ^
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1

```

**Comment by tewalds** [comment]
On Linux I found something similar sometimes happened if I didn't first do `pip install --upgrade pip`. Can you try that?

**Comment by xwzy** [comment]
I did this, but the problem still remains.

```
$ pip install --upgrade pip
Requirement already up-to-date: pip in ./anaconda/lib/python3.5/site-packages
```

**Comment by tewalds** [comment]
Maybe you need to install libsdl-dev or similar? I'm really not sure how macs work.

**Comment by ttdonovan** [comment]
@xwzy are you sure you have SDL2 installed? Try using Homebrew to install this package.

```
$ brew install sdl2
```

**Comment by xwzy** [comment]
Homebrew cannot install SDL2 correctly on my mac. Are there other solutions?
```
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall sdl2`

```

```
$ brew postinstall sdl2
==> Postinstalling sdl2
Error: parent directory is world writable but not sticky
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:92:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/cmd/postinstall.rb:32:in `run_post_install'
/usr/local/Homebrew/Library/Homebrew/cmd/postinstall.rb:12:in `block in postinstall'
/usr/local/Homebrew/Library/Homebrew/cmd/postinstall.rb:10:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/postinstall.rb:10:in `postinstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

**Comment by xwzy** [comment]
http://www.libsdl.org/download-2.0.php

I also have tried download sdl2 from above page and copy to /Library/Framework directory, but still get the same error.

**Comment by halflings** [comment]
@xwzy : This seems to address your issue.

https://stackoverflow.com/questions/41806977/cant-install-pygame-with-pip-as-there-is-an-error-whilst-runningvsetup-py-bdist

    pip install pygame==1.9.2

Unsure if pysc2 will work just the same with that version, but worth trying.

Otherwise try this:

    brew install sdl sdl_image sdl_mixer sdl_ttf portmidi

If brew still complains, follow these instructions to fix it (you will find homebrew is extremely useful anyway): https://github.com/Homebrew/legacy-homebrew/issues/39170#issuecomment-97367623

**Comment by xwzy** [comment]
@halflings Thanks.

**Comment by halflings** [comment]
No problem, you can close this issue if it was resolved.

**Comment by princ3raj** [comment]
@xwzy  it worked for me

**Comment by baiiii** [comment]
> @xwzy : This seems to address your issue.
> 
> https://stackoverflow.com/questions/41806977/cant-install-pygame-with-pip-as-there-is-an-error-whilst-runningvsetup-py-bdist
> 
> ```
> pip install pygame==1.9.2
> ```
> 
> Unsure if pysc2 will work just the same with that version, but worth trying.
> 
> Otherwise try this:
> 
> ```
> brew install sdl sdl_image sdl_mixer sdl_ttf portmidi
> ```
> 
> If brew still complains, follow these instructions to fix it (you will find homebrew is extremely useful anyway): [Homebrew/legacy-homebrew#39170 (comment)](https://github.com/Homebrew/legacy-homebrew/issues/39170#issuecomment-97367623)

nice! it close my issue, thank you~
