### ISSUE TITLE
Observation NamedDict RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by ai2010** [deepmind/pysc2#208]
I am handling the observation NamedDict object , obs, from the environment. Since I have 1 environment and 1 agent if print :
```
print('ob0: ',len(obs[0]),'--',type(obs[0]))
print('keys: ',obs[0].keys())
```
I rightfully get:
```
ob0:  17 -- <class 'pysc2.lib.named_array.NamedDict'>
keys:  dict_keys(['control_groups', 'build_queue', 'rgb_screen', 'action_result', 'cargo', 'available_actions', 'alerts', 'score_cumulative', 'multi_select', 'single_select', 'feature_screen', 'last_actions', 'game_loop', 'feature_minimap', 'rgb_minimap', 'player', 'cargo_slots_available'])
```
However if now I want to access the key 'feature_screen':
`print(obs[0]['feature_screen']`
I got the error:
`  File "/home/dstefanidis/.virtualenvs/wingman/lib/python3.5/site-packages/pysc2/lib/named_array.py", line 200, in _get_index
    return obj._index_names[0][index]
  File "/home/dstefanidis/.virtualenvs/wingman/lib/python3.5/site-packages/pysc2/lib/named_array.py", line 129, in __getattr__
    return self[name]
  File "/home/dstefanidis/.virtualenvs/wingman/lib/python3.5/site-packages/pysc2/lib/named_array.py", line 145, in __getitem__
    index = _get_index(obj, index)
  File "/home/dstefanidis/.virtualenvs/wingman/lib/python3.5/site-packages/pysc2/lib/named_array.py", line 196, in _get_index
    if isinstance(index, (numbers.Integral, slice)):
  File "/home/dstefanidis/.virtualenvs/wingman/lib/python3.5/abc.py", line 182, in __instancecheck__
    if subclass in cls._abc_cache:
RecursionError: maximum recursion depth exceeded`

Any help appreciated

Update:
Replacing manually the file named_array.py with the last one in this repo solved the problem. My pysc2 version is 2.0.1.

**Comment by mgvalverde** [comment]
Hi, 

As far I have cheked, the object `observation` is in the index 3.
Have a look to the output generated by: `obs._fields`
I get succesfully the `feature_screen` with `obs[3]['feature_screen']`.
Another easy way to call it using version 2.0 is `obs.observation.feature_screen`

I don't know if this solves your problem.

**Comment by silver-rush** [comment]
Same here. Essentially I could not interact with `obs` at all, including printing it or anything in it. Updating to latest master works.
