### ISSUE TITLE
Add building grid / pathing grid observation

### ISSUE THREAD

**Issue by dorthrithil** [deepmind/pysc2#210]
A human player can see a placement grid when he tries to place a building. This is not available in any observation in pysc2 currently as far as I know. This information would be really helpful and would solve many placement failures that we are facing currently. 

For example on Catalyst there are pipes around the players starting locations that have a path blocking property. These pipes are however not visible in any feature layer (height, units etc). This leads to an agent thinking that the location is buildable which is however not true.

**Comment by yanntm** [comment]
The query API offers building placement information

**Comment by tewalds** [comment]
These are now added.

**Comment by JulianGmp** [comment]
I know this issue has been closed for months now, but I wanted to ask if there's a chance of getting a simple example for this, since I wasn't able to find much documentation, and it would make building management a lot easier.

**Comment by yanntm** [comment]
Hi, I'm not sure about what the patch was, but concerning query API : 
https://github.com/yanntm/YoBot/blob/master/Placement.cpp#L51-L77
these examples show how to use it, the first method determines if a location is buildable, the second one finds a buildable location within a certain distance of a point.
Note in this code I also have a notion of "reserved" spots (e.g. between minerals and a base, or places below cliffs) where I don't want to build even though it is possible, but you can just get rid of that part.

**Comment by JulianGmp** [comment]
That looks like what I need, but I am working in python, and some representation in pysc2 would be great. I'm not sure how I would call the query API from C++ inside of python/pysc2.

As mentioned from tewalds:
> These are now added.

This should be an option?
Initially I thought it would be `obs.observation.feature_screen.buildable`, but that seems to only contain ones, even though there are buildings on screen. ([Screenshot](https://i.imgur.com/2PoLYDh.png))

I looked at the commits around 2020-09-27, and none of them seem to mention this topic.
There's also an `AgentInterfaceFormat` parameter `show_placeholders` described as `Whether to show buildings that are queued for construction.`, but I couldn't find any mentions of that keyword in the repository that lead anywhere.

I just don't know where to continue with this, surely DeepMind uses the ingame building grid to find building locations too, right?
