### ISSUE TITLE
Argument is out of range for action...

### ISSUE THREAD

**Issue by ai2010** [deepmind/pysc2#211]
I am using pysc2 version 2.0.1 and I'm running a similation using both screen and features set to 34 like that:

` parser.add_argument("--feature_screen_size", type=int, default=34)
    parser.add_argument("--feature_minimap_size", type=int, default=34)
    #action space features 1, rgb 2 (needed if both rgb and features are on)
    parser.add_argument("--action_space", type=str, default='features')
    
    parser.add_argument("--rgb_screen_size", type=str, default="34")
    parser.add_argument("--rgb_minimap_size", type=str, default="34")
    
    parser.add_argument("--use_feature_units", type=bool, default=True)
    parser.add_argument("--disable_fog", type=bool, default=True)`

Now randomly the step function 'obs = env.step([data])' returns an error like:
`  File "/home/dstefanidis/miniconda3/lib/python3.6/site-packages/pysc2/lib/features.py", line 970, in transform_action
    func, func_call.arguments))
ValueError: Argument is out of range for 331/Move_screen (3/queued [2]; 0/screen [0, 0]), got: [[0], [29, 34]]`

I checked the features.py file and the size of the space, 'sizes', is always fixed to 34 (correctly) but the action call acts for some reasons in a larger space... Any help appreciated.

**Comment by tewalds** [comment]
In case you dind't already figure it out, the value must be less than the max, not less or equal to max.
