### ISSUE TITLE
building queue for multiselect

### ISSUE THREAD

**Issue by natangold85** [deepmind/pysc2#216]
hello, in the game, when you multi select a training buiding you can see the size of the building queue for all buildings selected. the queue is only include the size of the queue for each building selected. 
is there any way to retrieve this information through pysc2 environment?
thanks

**Comment by SoyGema** [comment]
Hi @natangold85 ,
As you might know, pySC2 mimics human playing behaviour. 
When you play Starcraft II , I think you should select each building to build units.

You can do the following 
- Select all buildings and see queues
- Select the building 
- Build the unit 

Please let me know if this answer your question . 
Thanks!

**Comment by alkurbatov** [comment]
>When you play Starcraft II , I think you should select each building to build units.

Not necessarily. You can select group of buildings (multy select) or use a control group and click 'train something' button. The game will distribute your orders among the selected buildings.

**Comment by SoyGema** [comment]
Then is a game-bug right ?

**Comment by natangold85** [comment]
this option is available in the star craft2 game. i don't know if the bug is in the blizzard interface or yours but when you train unit in multiselect the training is distibuted equally in the selected buildings. try it and see.

thanks

**Comment by tewalds** [comment]
This is the same bug that is fixed in 4.6.0.
