### ISSUE TITLE
a bug in training via multi select?

### ISSUE THREAD

**Issue by natangold85** [deepmind/pysc2#217]
hello, i think maybe there is a bug when i train a soldier after i selected all building of the same type.
in the game if i multi select production building when i train soldiers the training will disperse equally among all buildings. for example, if i have 2 simple barracks and 1 with a reactor. each soldier i will train will go to the shortest queue among all barracks.
this doesn't seem to happen in my agent. after i multiselect all barracks i train an army (via quick training actions) and it seems all training is concentrating on one building . when the queue limit reach on this building training will be on a different building etc.

**Comment by SoyGema** [comment]
So you don´t get an error in the execution  but the queue doesn´t seem to work , Right ?
Are you sure that in your code you are selecting the buildings (barracks) and building in each one coherently?

Can you show the logic of the code ?
I am trying to know if it might be a game bug or not

**Comment by natangold85** [comment]
for my project in order to solve the game i'm creating hierarchical agents. each agent have his own mini game to expert in his decision making. this is the code of the train_agent whose purpose is only to train soldiers in the production buildings

**Comment by tewalds** [comment]
This is a bug in the game, which should be fixed in 4.6.0 and higher.
