### ISSUE TITLE
What do the 4 options for "select_point_act" arg in action function "select_point" do?

### ISSUE THREAD

**Issue by davidleejy** [deepmind/pysc2#221]
Hello.

```
import pysc2
for action in pysc2.lib.actions.FUNCTIONS:
    print(action)
```
Prints
```
...
2/select_point (6/select_point_act [4]; 0/screen [0, 0])
...
```

What do the 4 options for "select_point_act" arg in the action function "select_point" do?

My guess is that the options are:
**left-click**: "select"
**shift + left-click**: "toggle"
**right-click**: "move/attack, no queue"
**shift + right-click**: "move/attack, queue"
Not sure of the mapping between these to the indexes 0 to 3.

Thanks for helping.

**Comment by natangold85** [comment]
i'm not the one in charge here but from actions.py the enum is:

SELECT_POINT_ACT_OPTIONS = [
    ("select", sc_spatial.ActionSpatialUnitSelectionPoint.Select),
    ("toggle", sc_spatial.ActionSpatialUnitSelectionPoint.Toggle),
    ("select_all_type", sc_spatial.ActionSpatialUnitSelectionPoint.AllType),
    ("add_all_type", sc_spatial.ActionSpatialUnitSelectionPoint.AddAllType),
]
