### ISSUE TITLE
Why does the linux UI visualization window get smaller each game?

### ISSUE THREAD

**Issue by evdcush** [deepmind/pysc2#222]
The game visualization starts out at the dimensions specified at `feature_dimensions=feature.Dimensions`, but after each game, the visualization UI window gets about 15% smaller than the previous, until it's just this absurdly small thumbnail.

**Comment by SebastianBelkner** [comment]
Is there a reason why you restart the UI after each episode?
Workaround:
Using the sc2_env.SC2Env.reset() method resets the game without restarting the UI

**Comment by SebastianBelkner** [comment]
#202

**Comment by tewalds** [comment]
Is this still a problem in the version from git?

**Comment by GuilhermeMangueira** [comment]
Yes, and when i use the reset method above it raises 

> TypeError: reset() missing 1 required positional argument: 'self'
