### ISSUE TITLE
Resetting replay data once the controller gets restarted

### ISSUE THREAD

**Issue by gal-leibovich** [deepmind/pysc2#224]
Hi,

I'm looking for a way to reset the replay data, being aggregated internally by the controller, every time the pysc2 environment gets reset. 

Glancing through the code, it seems not supported. 
RemoteController.save_replay() [called by pysc2.env.sc2_env.save_replay()] gets the internally buffered data out of several episodes stitched together. Is it possible to reset the internal buffer every once in a while, by the user? 

The end goal is to be able to save replays of separate episodes instead of just one very long replay, which is a concatenation of many different episodes being played. 

Thanks!
Gal

**Comment by tewalds** [comment]
The only way is to create a new game instead of doing a restart. Note this is only a problem for minigames.
