### ISSUE TITLE
Looking for contribution

### ISSUE THREAD

**Issue by balazsbme** [deepmind/pysc2#225]
Hey guys, 

I am a Computer engineer, and I am very interested in sc2 ai (altough I don't have professional experience with machine learning), and I happen to know Python and play starcaft on platinum level. 

I would love to contribute some to the project to help researchers work with it. What can I contribute, what is the best way to enrich it's features, make it more valuable for researchers? 

Something most interesting would be which requires some sc2 knowledge and programming. E. g. new more advanced mini games? Would it be a nice contribution? 

Thanks, 
Balázs

**Comment by innerlee** [comment]
This issue https://github.com/deepmind/pysc2/issues/204 is a very nice one.

**Comment by tewalds** [comment]
I'd recommend joining the discord channel.
