### ISSUE TITLE
Feature Request - Blueprint Buildings

### ISSUE THREAD

**Issue by MicioGatto** [deepmind/pysc2#226]
The world state of having blueprint buildings is distinct from them either not existing or the buildings being built.  Given a state, if the best action to take is 'Build a Supply Depot', then this will be true until the state changes, which will not be possible to detect until the blueprint is converted to a building.  This means that an agent may choose to repeat the same action many times - This could be the same SCV trying to build a supply depot in multiple places (if placement is not deterministic), or multiple SCV's building many supply depots.  If the goal of the reward structure is to keep the supply limit within certain bounds then all too often the agent will find that the action to do this results in them overshooting on how much supply they need to build, polluting the signal because the best action will receive an incorrect reward.  My naïve solution would be to include blueprints in feature_units and distinguish them from other buildings by giving them a build_progress value of 0.

**Comment by tewalds** [comment]
This is called a placeholder, and is now added.
