### ISSUE TITLE
Unable to use keyboard shortcut in linux version

### ISSUE THREAD

**Issue by PeiYingjun** [deepmind/pysc2#229]
version of pysc2 is 2.0.1
I can select some units and make them move with mouse, 
yet when I push the button 's'(stop) , there is no reaction, so do other buttons .

**Comment by SerafimC** [comment]
Does the shortcuts `F4`, `F5` and `F9` works?

**Comment by PeiYingjun** [comment]
> Does the shortcuts `F4`, `F5` and `F9` works?
> Which linux distro are you using?

seems not work, distro is Ubuntu 18.04

**Comment by tewalds** [comment]
Do you have any more details? Did you get it working?

**Comment by PeiYingjun** [comment]
> Do you have any more details? Did you get it working?

It still does not work on my laptop, so I've been using pysc2 on my lab's computer
