### ISSUE TITLE
python -m pysc2.bin.agent does not work well on mac?

### ISSUE THREAD

**Issue by etali** [deepmind/pysc2#23]
when I ran "python -m pysc2.bin.agent --map Simple64", the SCII window shown, but the pygame window did not show itself and its icon kept jumping.

<img width="603" alt="screen shot 2017-08-12 at 12 34 17 pm" src="https://user-images.githubusercontent.com/1567021/29237902-ab78ec2c-7f5a-11e7-894a-730ffe64c456.png">

**Comment by tewalds** [comment]
Are you running from pypi or git? This might be fixed in 509f607.

**Comment by etali** [comment]
Thanks. I reinstalled pysc2 package from git, and the bug mentioned above has been fixed.
