### ISSUE TITLE
Exceptions.WebSocketConnectionClosedException: Connection is already closed.

### ISSUE THREAD

**Issue by SerafimC** [deepmind/pysc2#231]
Hi,
I'm using Fedora 27. When I play the game "as a human", I'm getting the error:

> Failed to get the resolution from xrandr

I already tried to apply [this solution](https://github.com/deepmind/pysc2/issues/202), but didn´t work.

The problem occurs also in the `renderer_human.py` file on the lines 201-205.
It seens like that the string `xrandr_query ` has not the `bconnected primary` property. The list `sizes` is empty and a 'pointer invalid' exception occurs.

@EDIT1

So.. I modified the line to take the correct `xrandr --query` string from Fedora. Now, i got another error:

> websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

any idea?

**Comment by tewalds** [comment]
Can you send a PR with the fix for fedora, especially if it works for ubuntu as well?

WebSocketConnectionClosedException is a catch all for when SC2 crashes, so you'll need to provide more information than that.
