### ISSUE TITLE
All tests in pysc2/tests folder failed by the old "absl.flags._exceptions.UnparsedFlagAccessError:" error

### ISSUE THREAD

**Issue by mongolia19** [deepmind/pysc2#233]
Hi!
Does anyone get the same problem like me: I clone the newest repo of pysc2, and installed all the libs that it asks for. Here is my install list(I am sure I have made sure everything is prepared as told):
Requirement already satisfied: absl-py>=0.1.0 in c:\programdata\miniconda3\lib\site-packages (from PySC2==2.0.1)
Requirement already satisfied: enum34 in c:\programdata\miniconda3\lib\site-packages (from PySC2==2.0.1)
Requirement already satisfied: future in c:\programdata\miniconda3\lib\site-packages (from PySC2==2.0.1)
Requirement already satisfied: mock in c:\programdata\miniconda3\lib\site-packages (from PySC2==2.0.1)
Requirement already satisfied: mpyq in c:\programdata\miniconda3\lib\site-packages (from PySC2==2.0.1)
Requirement already satisfied: numpy>=1.10 in c:\programdata\miniconda3\lib\site-packages (from PySC2==2.0.1)
Requirement already satisfied: portpicker>=1.2.0 in c:\programdata\miniconda3\lib\site-packages (from PySC2==2.0.1)
Requirement already satisfied: protobuf>=2.6 in c:\programdata\miniconda3\lib\site-packages (from PySC2==2.0.1)
Requirement already satisfied: pygame in c:\programdata\miniconda3\lib\site-packages (from PySC2==2.0.1)
Requirement already satisfied: requests in c:\programdata\miniconda3\lib\site-packages (from PySC2==2.0.1)
Requirement already satisfied: s2clientprotocol>=4.6.0.67926.0 in c:\programdata\miniconda3\lib\site-packages (from PySC2==2.0.1)
Requirement already satisfied: six in c:\programdata\miniconda3\lib\site-packages (from PySC2==2.0.1)
Requirement already satisfied: sk-video in c:\programdata\miniconda3\lib\site-packages (from PySC2==2.0.1)
Requirement already satisfied: websocket-client in c:\programdata\miniconda3\lib\site-packages (from PySC2==2.0.1)
Requirement already satisfied: whichcraft in c:\programdata\miniconda3\lib\site-packages (from PySC2==2.0.1)
Requirement already satisfied: pbr>=0.11 in c:\programdata\miniconda3\lib\site-packages (from mock->PySC2==2.0.1)
Requirement already satisfied: setuptools in c:\programdata\miniconda3\lib\site-packages (from protobuf>=2.6->PySC2==2.0.1)
Requirement already satisfied: scipy in c:\programdata\miniconda3\lib\site-packages (from sk-video->PySC2==2.0.1)

Then I install the pysc2 by "pip install -e . " in its own repo. 
But I run the tests scripts in the tests dirictory, every test is failed by the old error:
**absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag sc2_run_config before flags were parsed.**
    run_config = run_configs.get()
  File "C:\Users\Administrator\PycharmProjects\pysc2\pysc2\run_configs\__init__.py", line 39, in get
    if FLAGS.sc2_run_config is None:  # Find the highest priority as default.
  File "C:\ProgramData\Miniconda3\lib\site-packages\absl\flags\_flagvalues.py", line 500, in __getattr__
    raise _exceptions.UnparsedFlagAccessError(error_message)
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag sc2_run_config before flags were parsed.

Can anyone can pass the tests on version 2.o.1? If so pls tell me your versions of dependencies？I am stuck here， help！

**Comment by Gusgus01** [comment]
@mongolia19 If you are still interested, you can run the tests by using 
`python pysc2/bin/run_tests.py`
as recommended in the README.txt (also worth noting you possibly need to set the env variable SC2Path if the executable is somewhere other than the default, and that you need to download all the maps and mini_games and put them in the right place).

The bin file exists since they use abseil flags and need to use absl.testing to execute their tests. You can also run each file individually, just by executing the file using python since their mains have been set up correctly.
