### ISSUE TITLE
multi-agent fails on Windows

### ISSUE THREAD

**Issue by TaehwanKwon** [deepmind/pysc2#234]
Hi, I tested "python -m pysc2.bin.agent --map Simple64 --agent2 pysc2.agents.random_agnet.RandomAgent" but it fails.

I tried to find the source of failure and I found out it fails from run_parallell.py in pysc2.env.

It fails at "done, not_done = futures.wait(futs, self._timeout, futures.FIRST_EXCEPTION)", around 65 lines.

I printed the "done" and "not_done"  and it shows below result.

done:  set([<Future at 0x80f2690 state=finished raised ConnectionError>]) not_done :  set([<Future at 0x80f2450 sta te=running>])

How can I fix it?

**Comment by Pooch11** [comment]
I don't know if this is related but there is a spelling error on the agent you are trying to invoke. 
I just did a fresh install and was unable to reproduce this on Windows 
From the ReadMe
python -m pysc2.bin.agent --map Simple64 --agent2 pysc2.agents.random **_agent.** RandomAgent

> "python -m pysc2.bin.agent --map Simple64 --agent2 pysc2.agents.random_agnet.RandomAgent"

**Comment by TaehwanKwon** [comment]
@Pooch11 
Oh, that's just typo in here.
Yeah, it doesn't work in Windows :(
The interface for human player is not enough to play in linux..

**Comment by TaehwanKwon** [comment]
Here are the results that I found where it stops.

Server:
It stops at self._sock.recv() in _read() function in protocol.py.
After server's SC2 instance gets 'join' information.

I1015 11:35:58.000089 140076228245248 lan_sc2_env.py:69] Waiting for connection on 127.0.0.1:14380
I1015 11:36:04.924660 140076228245248 lan_sc2_env.py:71] Accepted connection from 127.0.0.1:34684
======================================
{'join_game': race: Random
options {
  raw: true
  score: true
  feature_layer {
    width: 24.0
    resolution {
      x: 84
      y: 84
    }
    minimap_resolution {
      x: 64
      y: 64
    }
  }
  render {
    resolution {
      x: 256
      y: 256
    }
    minimap_resolution {
      x: 128
      y: 128
    }
  }
}
server_ports {
  game_port: 14381
  base_port: 14382
}
client_ports {
  game_port: 14383
  base_port: 14384
}
shared_port: 0
}
======================================
========request str sendted: 

And then it stops, SC2 instance doesn't respond.
Same thing happens at client SC2 instance, it also stops after getting 'join' information at same position.
(self._sock.recv() in _read() function in protocol.py)

Client: 
======================================
{'join_game': race: Random
options {
  raw: true
  score: true
  feature_layer {
    width: 24.0
    resolution {
      x: 84
      y: 84
    }
    minimap_resolution {
      x: 64
      y: 64
    }
  }
  render {
    resolution {
      x: 256
      y: 256
    }
    minimap_resolution {
      x: 128
      y: 128
    }
  }
}
server_ports {
  game_port: 14381
  base_port: 14382
}
client_ports {
  game_port: 14383
  base_port: 14384
}
shared_port: 0
}
======================================
========request str sendted: 


The Windows SC2 version is 4.6.0, build is 67296 and I guess the websocket message for SC2 instance for multi-player is somewhat become different.
Can somebody help me on this issue?

**Comment by TaehwanKwon** [comment]
I close this issue. It works fine on 4.6.2.
