### ISSUE TITLE
SC2 processes eating GPU memory

### ISSUE THREAD

**Issue by bjg2** [deepmind/pysc2#235]
This is how my GPU looks like when starting a training with 24 environments (one per CPU):

![image](https://user-images.githubusercontent.com/6639273/46807568-849e6280-cd6a-11e8-87a8-e61e01f98bb7.png)

SC2 processes are eating up my GPU memory because they are implicitly started with hardware rendering (lines 193 -> 203 in `run_configs/platforms.py`). When I comment out those lines everything still works for me with same speed as before, even --visualize, but the memory is not used up anymore:

![image](https://user-images.githubusercontent.com/6639273/46807207-af3beb80-cd69-11e8-8be0-7b817870a6d1.png)

As you can see, this is huge difference (~4gb of RAM in my case, which is ~35% of total). Can you please add a param for starting pysc2 not using the GPU? Currently the only solution I know of is commenting out these lines...

**Comment by bjg2** [comment]
realized that this is fixed in new version of SC2, closing.

**Comment by douglasrizzo** [comment]
I am currently having this problem. Could someone point out how can I get rid of SC2 instances using up my GPU memory?
