### ISSUE TITLE
Unit tag should not be stored as 'np.int32'

### ISSUE THREAD

**Issue by hkchengrex** [deepmind/pysc2#240]
From [this line](https://github.com/deepmind/pysc2/blob/a9f093493c4c77adb385602790a480e7f238b97d/pysc2/lib/features.py#L1013), the last item `u.tag` is stored as `np.int32`. It is also converted again as `np.int32` [here](https://github.com/deepmind/pysc2/blob/a9f093493c4c77adb385602790a480e7f238b97d/pysc2/lib/features.py#L1034).

From StarCraft II [protobuf](https://github.com/Blizzard/s2client-proto/blob/af895ef658fc79096bd63ce5bd4f020dcee995f8/s2clientprotocol/raw.proto#L90), the unit tag should be `uint64`. And they DO use tag beyond `int32`. Even in simple games like MoveToBeacon, the actual tag value differs from the stored tag. I have tried simply changing those two occurrences of `int32` to `int64` and it worked (so far). I believe this is a bug.

**Comment by tewalds** [comment]
This should be fixed.
