### ISSUE TITLE
Screen reduction and Human_renderer issue - Linux

### ISSUE THREAD

**Issue by GuilhermeMangueira** [deepmind/pysc2#245]
Hi, im on Ubuntu 18.04 and at every new phase the screen gets smaller. Also the renderer_human.py launches an error and does not start the "human visualization", the error is

> E1107 13:46:06.872022 140038527543104 renderer_human.py:205] Failed to get the resolution from xrandr.

i tried the solution at [https://github.com/deepmind/pysc2/issues/222](url) but doesnt work. Any ideas? Apart from that the AI seems to be working fine

**Comment by tewalds** [comment]
This is a duplicate of #222
