### ISSUE TITLE
Is it possible to set player number in agent_remote / play_vs_agent?

### ISSUE THREAD

**Issue by dulex123** [deepmind/pysc2#247]
I have created a minimap where premade protoss unit is given to player 1 and two terran units are given to player 2, is it possible to declare in agent_remote or play_vs_agent code which player (1 or 2) will the human be?

**Comment by tewalds** [comment]
It might be easier to change the map to do the reverse... It's certainly possible to change agent_remote or play_vs_agent to swap things, but it means changing who does RequestCreateGame, which means trusting the agent to create it, sending more data across, or disconnecting from the websocket, which is a bit flaky.
