### ISSUE TITLE
Run pysc2 from inside Spyder

### ISSUE THREAD

**Issue by Migdalin** [deepmind/pysc2#249]
This is maybe a documentation request as much as anything.  How do I invoke the Agent's main function programmatically, so that I can step through in the debugger?  There appear to be a lot of command-line arguments, but the Agent's main() ignores the argv.  Probably there's a global variable I need to use, but I haven't been able to suss out which one.

**Comment by inoryy** [comment]
@Migdalin it's actually quite simple to invoke pysc2 programmatically even if you don't make use of absl (but you do have to have it installed though). Here's for I do it for example: https://github.com/inoryy/reaver-pysc2/blob/master/reaver/envs/sc2.py#L38-L55

**Comment by Migdalin** [comment]
Sounds good.  I didn't want to lose the startup logic from the pysc2.bin.agent, so I went this way:

```
import pysc2 as p2
import pysc2.bin.agent as agentMain
from absl import flags
from absl import app

def initFlags():
    flags.FLAGS.map = 'Simple64'
    flags.FLAGS.agent = 'my_agent.MyAgent'
    flags.FLAGS.agent_race = 'terran'
    flags.FLAGS.max_agent_steps = 0
    flags.FLAGS.render = False
    flags.FLAGS.

def entrypoint(argv):
    initFlags()
    agentMain.main('')

app.run(entrypoint)

```

**Comment by tewalds** [comment]
I'd recommend forking bin/agent.py and change it as you'd like. A few things depend on absl flags, but there's no reason you can't call the environment/libraries from your own main script.
