### ISSUE TITLE
Enhancement Request:  Full screen and UI

### ISSUE THREAD

**Issue by Migdalin** [deepmind/pysc2#250]
Requesting an API where we receive the full game screen, and can perform actions via "left click," "Press A", etc.

You added support for RGB pixels, but the "screeen" and "minimap" are still separated.  Also, most of the defined actions are specified with abstractions, rather than in terms of what a human would literally do.  Like "select_point()" is good, but is still an abstraction compared to "mouse.left_click(x,y)" or "keyboard.key_press("A").  

These intervening abstractions represent assumptions being made by us, and indicate a lack of faith in the neural net to figure the game out on its own.

**Comment by tewalds** [comment]
This needs support from Blizzard, so would be better requested from https://github.com/Blizzard/s2client-proto .
