### ISSUE TITLE
max_agent_steps flag is ignored

### ISSUE THREAD

**Issue by primus852** [deepmind/pysc2#252]
I have tried three different calls:
`python -m pysc2.bin.agent --map Simple64 --agent refined.DeepAgent --agent_race terran --norender`
`python -m pysc2.bin.agent --map Simple64 --agent refined.DeepAgent --agent_race terran --norender --max_agent_steps 0 0`
`python -m pysc2.bin.agent --map Simple64 --agent refined.DeepAgent --agent_race terran --norender max_agent_steps 0 50000`
all three result in a draw at 28800 steps, what can I do?

**Comment by tewalds** [comment]
try:
`
python -m pysc2.bin.agent --map Simple64 --agent refined.DeepAgent --agent_race terran --norender --max_agent_steps 50000`
