### ISSUE TITLE
Is there an actual "Attack_minimap" action that works as it does for human players?

### ISSUE THREAD

**Issue by laedvin** [deepmind/pysc2#258]
For human players, attacking a point on the minimap issues an "attack move" command that always targets the ground at that point; the selected army will then move towards that point and attack everything in its way. In PySC2, however, `Attack_minimap` seems to issue an "attack" command at that point as if it were targeting the screen (had the player centered its camera on that point).

The difference is that if there is a unit at that point `Attack_minimap` will issue an attack on that unit, meaning that the selected army will ignore everything else and just try to kill the targeted unit. 

So my question is, is there an action that emulates the human "attack minimap" behavior in that it only targets the ground?

**Comment by tewalds** [comment]
Hmm, that's unfortunate, but no, that'd be a bug in the game.
