### ISSUE TITLE
Mac: libc++abi.dylib: terminating with uncaught exception of type NSException

### ISSUE THREAD

**Issue by mfalkiewicz** [deepmind/pysc2#26]
The SC2 window starts, but no actions are taken and the console gives an error (both on Python2 and Python3). However, the game and the API run fine if I start it with pysc2.bin.play.

> python2 -m pysc2.bin.agent --map CollectMineralShards --agent pysc2.agents.scripted_agent.CollectMineralShards
NSWindowEdgeResizing is off!
2017-08-12 18:46:22.857 Python[30716:671361] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffd3a9c2cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffe88ac48d objc_exception_throw + 48
	2   AppKit                              0x00007fffd1c87e82 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 4480
	3   libSDL-1.2.0.dylib                  0x00000001113539dc QZ_PumpEvents + 358
	4   libSDL-1.2.0.dylib                  0x0000000111333866 SDL_PumpEvents + 35
	5   libSDL-1.2.0.dylib                  0x0000000111333a44 SDL_EventState + 197
	6   libSDL-1.2.0.dylib                  0x00000001113522dd SDL_JoystickEventState + 41
	7   joystick.so                         0x00000001115ebdb2 joy_autoinit + 50
	8   Python                              0x000000010f8c04a1 PyObject_Call + 98
	9   Python                              0x000000010f942ea8 PyEval_CallObjectWithKeywords + 166
	10  base.so                             0x0000000111323c6c init + 268
	11  Python                              0x000000010f93d651 PyEval_EvalFrameEx + 9961
	12  Python                              0x000000010f93ad73 PyEval_EvalCodeEx + 1621
	13  Python                              0x000000010f8de9e3 function_call + 330
	14  Python                              0x000000010f8c04a1 PyObject_Call + 98
	15  Python                              0x000000010f93fc9a PyEval_EvalFrameEx + 19762
	16  Python                              0x000000010f93ad73 PyEval_EvalCodeEx + 1621
	17  Python                              0x000000010f8de9e3 function_call + 330
	18  Python                              0x000000010f8c04a1 PyObject_Call + 98
	19  Python                              0x000000010f93fc9a PyEval_EvalFrameEx + 19762
	20  Python                              0x000000010f93ad73 PyEval_EvalCodeEx + 1621
	21  Python                              0x000000010f943581 fast_function + 298
	22  Python                              0x000000010f93d54b PyEval_EvalFrameEx + 9699
	23  Python                              0x000000010f93ad73 PyEval_EvalCodeEx + 1621
	24  Python                              0x000000010f943581 fast_function + 298
	25  Python                              0x000000010f93d54b PyEval_EvalFrameEx + 9699
	26  Python                              0x000000010f93ad73 PyEval_EvalCodeEx + 1621
	27  Python                              0x000000010f8de9e3 function_call + 330
	28  Python                              0x000000010f8c04a1 PyObject_Call + 98
	29  Python                              0x000000010f8cb03a instancemethod_call + 162
	30  Python                              0x000000010f8c04a1 PyObject_Call + 98
	31  Python                              0x000000010f9084e5 slot_tp_init + 68
	32  Python                              0x000000010f905558 type_call + 182
	33  Python                              0x000000010f8c04a1 PyObject_Call + 98
	34  Python                              0x000000010f93d604 PyEval_EvalFrameEx + 9884
	35  Python                              0x000000010f93ad73 PyEval_EvalCodeEx + 1621
	36  Python                              0x000000010f8de9e3 function_call + 330
	37  Python                              0x000000010f8c04a1 PyObject_Call + 98
	38  Python                              0x000000010f93fc9a PyEval_EvalFrameEx + 19762
	39  Python                              0x000000010f94351c fast_function + 197
	40  Python                              0x000000010f93d54b PyEval_EvalFrameEx + 9699
	41  Python                              0x000000010f94351c fast_function + 197
	42  Python                              0x000000010f93d54b PyEval_EvalFrameEx + 9699
	43  Python                              0x000000010f93ad73 PyEval_EvalCodeEx + 1621
	44  Python                              0x000000010f8de9e3 function_call + 330
	45  Python                              0x000000010f8c04a1 PyObject_Call + 98
	46  Python                              0x000000010f8cb03a instancemethod_call + 162
	47  Python                              0x000000010f8c04a1 PyObject_Call + 98
	48  Python                              0x000000010f942ea8 PyEval_CallObjectWithKeywords + 166
	49  Python                              0x000000010f96fc2c t_bootstrap + 70
	50  libsystem_pthread.dylib             0x00007fffe93ab93b _pthread_body + 180
	51  libsystem_pthread.dylib             0x00007fffe93ab887 _pthread_body + 0
	52  libsystem_pthread.dylib             0x00007fffe93ab08d thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by ttdonovan** [comment]
I can confirm and am experiencing the same exception with `pysc2.bin.agent` my supposition is that the issue has something to do with `sc2_env.SC2Env`.

**Comment by tylerwhipple** [comment]
Install from git, should be fixed

#2

**Comment by mfalkiewicz** [comment]
It works now. This can be closed now.
