### ISSUE TITLE
Can we terminate the running thread in concurrent.futures ? pysc2 does not support it

### ISSUE THREAD

**Issue by hjdesai2** [deepmind/pysc2#261]
https://github.com/deepmind/pysc2/blob/master/pysc2/lib/run_parallel.py

in this code https://github.com/deepmind/pysc2/blob/master/pysc2/lib/run_parallel.py#L71 this is only cancel thread if it's not started just submitted.

How to make this work if there are multiple threads and one thread throws exception and others have started already but want to forcefully terminate it ?

**Comment by tewalds** [comment]
I'm not sure you can... I struggled to get the futures to work well.
