### ISSUE TITLE
pysc2 2.0.2 can't run in starcraft2 4.8.4 (windows 10)

### ISSUE THREAD

**Issue by Jonarain** [deepmind/pysc2#263]
I tried to run pysc2 random agent

ran command in pycharm terminal

no errors was showed in terminal

but a "Failed to load" window appeared, and game can't start

"Critical error during loading process.Required library 'icuuc52.dll' does not exist"

I started game from Battle.net , game started successfully.

**Comment by Freshpbj** [comment]
Same issue, checked the ~/Starcraft2/Support and ~/Support64, both folders have icuuc52.dll in them.
Was working on previous version of SC2.

**Comment by Jonarain** [comment]
> Same issue, checked the ~/Starcraft2/Support and ~/Support64, both folders have icuuc52.dll in them.
> Was working on previous version of SC2.

Thank you very much! I found icuuc52.dll.
Should I copy it and paste into other folders?

**Comment by Freshpbj** [comment]
I meant I also have the same problem you do. Error states that the file does not exist, but when i look in the folders it is there.
Maybe there is a path somewhere that changed when SC2 updated, I just made my first hello world about 3 weeks ago so this is a bit out of my league,

**Comment by zarater** [comment]
I have that problem right now. is there any suggestions? its in a support folder.
Im using windows 10

**Comment by Freshpbj** [comment]
If you are using PyCharm 2019.1 you need to downgrade to 2018.6

**Comment by Jonarain** [comment]
Thank you very much.
Sorry, I still don't understand how to mute the thread.
Could you please show me more details about how to fix this problem.




------------------ 原始邮件 ------------------
发件人: "Timo Ewalds"<notifications@github.com>; 
发送时间: 2019年5月14日(星期二) 凌晨2:11
收件人: "deepmind/pysc2"<pysc2@noreply.github.com>; 
抄送: "徐凡超"<354392089@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [deepmind/pysc2] pysc2 2.0.2 can't run in starcraft2 4.8.4(windows 10) (#263)




Closed #263.

**Comment by ongunuzaymacar** [comment]
Recently switched to PyCharm so I really don't understand the issue, but simply executing the .py file from your terminal works fine.

**Comment by radiantprism** [comment]
Me too here. I made simple demo code and it doens't work on Pycharm. but it works on Python IDLE.
