### ISSUE TITLE
line 185, in __init__     raise ValueError("All arguments must be passed as keyword arguments.") 

### ISSUE THREAD

**Issue by zarater** [deepmind/pysc2#264]
- I'm on step 4 in the read me file. 
- I just downloaded today and I was wondering if anyone knows what this means. 

- on the debug console using pycharm:

`D:\Python37\python.exe C:/Users/zarat/Downloads/A-Guide-to-DeepMinds-StarCraft-AI-Environment-master/train_mineral_shards.py
pygame 1.9.6

Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:/Users/zarat/Downloads/A-Guide-to-DeepMinds-StarCraft-AI-Environment-master/train_mineral_shards.py", line 51, in <module>
    main()
  File "C:/Users/zarat/Downloads/A-Guide-to-DeepMinds-StarCraft-AI-Environment-master/train_mineral_shards.py", line 24, in main
    visualize=True) as env:
  File "D:\Python37\lib\site-packages\pysc2\env\sc2_env.py", line 185, in __init__
    raise ValueError("All arguments must be passed as keyword arguments.")
ValueError: All arguments must be passed as keyword arguments.

Process finished with exit code 1`

**Comment by zarater** [comment]
also, I have sc2 in my d drive and same with python, pycharm. I'm using my pycharm 3.7 as virtual environment as default for interpreter.

**Comment by tewalds** [comment]
I'm not sure which readme you're talking about, but it must be pretty old at this point. Either way, the problem is it's passing some arguments as positional arguments instead of keyword arguments.
