### ISSUE TITLE
Correct Terminology Food vs Supply

### ISSUE THREAD

**Issue by TuringsEgo** [deepmind/pysc2#27]
In the feature panel, the word "food" is used to describe supply. This is confusing even for someone who routinely plays SC2, just use the correct terminology.

**Comment by zsluedem** [comment]
Seems like in war3 ,food is usedfor every races. I supposed it is kind of like Blizzard's custom and deepmind just use as it is~! SO food is fine..

**Comment by tewalds** [comment]
This is in the underlying protocol (https://github.com/Blizzard/s2client-proto). @KevinCalderone any thoughts?

**Comment by KevinCalderone** [comment]
The engine internally refers to this as food, which is probably why we ended up referring to it as food everywhere in the protocol.

I think both terminologies are fine. Supply may be slightly more correct if you are just a player of the game, but then it may be confusing if you try to look up things in the editor where everything is called food. I would just take the path of least resistance and keep calling it food.
