### ISSUE TITLE
Attack_screen coordinates issue

### ISSUE THREAD

**Issue by amritas02** [deepmind/pysc2#275]
Hello All, 

I am very confused about the coordinate space in pysc2. What is the top left, top right, bottom left and bottom right coordinates when using actions.FUNCTIONS.Attack_screen?

**Comment by ethan052** [comment]
I guess the default screen width and height are both 84 (start from 0).
You can search "84" in this repository.

(0, 0) should be (left, top), and (83,83) should be (right, bottom).

I guess actions.Functions.Attack_screen uses the same screen parameter as actions.Functions.select_point.
You can read the _FUNCTIONS and FUNCTION_TYPES in pysc2/lib/actions.py

The cmd_screen function defined in pysc2/lib/actions needs (x, y) or [x, y] as its screen parameter.

Arrays of obs.observation.feature_screen are row-based.
For example, if obs.observation.feature_screen.unit_type[y][x] != 0, using actions.Functions.select_point with (x,y) "may" successfully select a unit.
