### ISSUE TITLE
When replay fails (SC2 4.9.1)

### ISSUE THREAD

**Issue by n-ai-up8-edu** [deepmind/pysc2#276]
Dear All,

Usually it is pleasant to generate mpq files from a bot game and look at them after, by moving wisely the camera independently of the bot move_camera. Unfortunately the replay of such pysc2 files is no more working. Remember that the replay files, are written by agent.bin.play.

My current SC2 version is 4.9.1 and i am using pysc2 which is 4.8.x compatible.

When I am launching the replay with BattleNet, connected or not, SC2 tells me that it cant play the file.

Trying to solve this problem, I tried many things :
1) to add arguments inside BattleNet interface, by adding something like this as command line argument :
-dataVersion B6D73C85DFB70F5D01DEABB2517BF11C
(that is supposed to call Base65384 version)

2) to see if it is supported by pysc2 dev branch (probably not because it did the same...)

3) to modify pysc2/run_configs/lib.py file,
by using pysc2/bin/gen_versions.py and copy-past new versions with keys into the file
...
Version("4.8.5", 73559, "B2465E73AED597C74D0844112D582595", None),
Version("4.8.6", 73620, "AA18FEAD6573C79EF707DF44ABF1BE61", None),
Version("4.9.0", 74071, "70C74A2DCA8A0D8E7AE8647CAC68ACCA", None),
...

4) to do the same with version 4.9.1 from reading logs of the launcher
...
Version("4.9.1", 74456, "218CB2271D4E2FA083470D30B1A05F02", None),

5) to use many of these data version numbers inside the BattleNet interface

Thus if you have any ideas about this problem, please let me know.

Best

**Comment by tewalds** [comment]
Does it work with the newest versions of the game and pysc2 now?
