### ISSUE TITLE
This is more like question

### ISSUE THREAD

**Issue by SungyunPark** [deepmind/pysc2#278]
I am curious about whether I can make an agent do chat in game. I could make a simple agent that plays Zerg in game and I want to know it is possible to make an agent chat with players or (if there is) alliance.
And if I can, is it possible another player can get the message that agent chat in game. The goal I think of is cooperative agent with another agent... so like if an agent chat "attack stalker", alliance agent only attack stalker.

Thank you for reading rough question...

**Comment by tewalds** [comment]
Yup, you can do that with RequestChat in the protobuf, or send_chat_messages on the SC2Env.
