### ISSUE TITLE
does the linux package support the creation of .SC2Bank files?

### ISSUE THREAD

**Issue by veenhouse** [deepmind/pysc2#279]
I have a niche need to allow my map to create bank files on a linux machine. Currently I am able to make these bank files in a windows environment but can not be sure they are being created in my linux environment. Does anyone know if this is at all possible?
If relevant I am running the 4.7.1 release of the linux binaries

**Comment by tewalds** [comment]
Maybe? I'm not sure what they are. The core engine is the same, but the interface to the game is different. If the map can generate those programmatically then possibly, otherwise no.
