### ISSUE TITLE
pysc2.lib.remote_controller.ConnectError: Failed to connect to the SC2 websocket. Is it up?

### ISSUE THREAD

**Issue by liangzid** [deepmind/pysc2#281]
I have this error and have no way:

D:\Administrator\Desktop\testSC2>python -m pysc2.bin.play --map Simple64
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
I0731 12:11:39.043779  8104 sc_process.py:110] Launching SC2: D:\风暴英雄\StarCraft II\Versions/Base75025\SC2_x64.exe -listen 127.0.0.1 -port 20
114 -dataDir D:\风暴英雄\StarCraft II\ -tempDir C:\Users\ADMINI~1\AppData\Local\Temp\sc-igrtanpm\ -displayMode 0 -windowwidth 640 -windowheight
480 -windowx 50 -windowy 50
I0731 12:11:39.080781  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 0, running: True
I0731 12:11:40.085839  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 1, running: True
I0731 12:11:41.085896  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 2, running: True
I0731 12:11:42.085953  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 3, running: True
I0731 12:11:43.087010  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 4, running: True
I0731 12:11:44.088068  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 5, running: True
I0731 12:11:45.089125  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 6, running: True
I0731 12:11:46.089182  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 7, running: True
I0731 12:11:47.090239  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 8, running: True
I0731 12:11:48.091296  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 9, running: True
I0731 12:11:49.091354  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 10, running: True
I0731 12:11:50.092411  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 11, running: True
I0731 12:11:51.094468  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 12, running: True
I0731 12:11:52.095525  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 13, running: True
I0731 12:11:53.096583  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 14, running: True
I0731 12:11:54.097640  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 15, running: True
I0731 12:11:55.097697  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 16, running: True
I0731 12:11:56.097754  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 17, running: True
I0731 12:11:57.098812  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 18, running: True
I0731 12:11:58.100869  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 19, running: True
I0731 12:11:59.100926  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 20, running: True
I0731 12:12:00.101984  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 21, running: True
I0731 12:12:01.104041  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 22, running: True
I0731 12:12:02.106098  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 23, running: True
I0731 12:12:03.106155  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 24, running: True
I0731 12:12:04.106213  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 25, running: True
I0731 12:12:05.107270  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 26, running: True
I0731 12:12:06.108327  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 27, running: True
I0731 12:12:07.109384  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 28, running: True
I0731 12:12:08.113442  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 29, running: True
I0731 12:12:09.113499  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 30, running: True
I0731 12:12:10.114556  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 31, running: True
I0731 12:12:11.116613  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 32, running: True
I0731 12:12:12.116671  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 33, running: True
I0731 12:12:13.119728  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 34, running: True
I0731 12:12:14.119785  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 35, running: True
I0731 12:12:15.119842  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 36, running: True
I0731 12:12:16.120900  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 37, running: True
I0731 12:12:17.121957  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 38, running: True
I0731 12:12:18.122014  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 39, running: True
I0731 12:12:19.124071  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 40, running: True
I0731 12:12:20.124129  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 41, running: True
I0731 12:12:21.124186  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 42, running: True
I0731 12:12:22.125243  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 43, running: True
I0731 12:12:23.126300  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 44, running: True
I0731 12:12:24.127358  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 45, running: True
I0731 12:12:25.128415  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 46, running: True
I0731 12:12:26.128472  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 47, running: True
I0731 12:12:27.131530  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 48, running: True
I0731 12:12:28.133587  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 49, running: True
I0731 12:12:29.133644  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 50, running: True
I0731 12:12:30.133701  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 51, running: True
I0731 12:12:31.133759  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 52, running: True
I0731 12:12:32.153817  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 53, running: True
I0731 12:12:33.237879  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 54, running: True
I0731 12:12:34.255937  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 55, running: True
I0731 12:12:35.256994  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 56, running: True
I0731 12:12:36.257051  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 57, running: True
I0731 12:12:37.257108  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 58, running: True
I0731 12:12:38.257166  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 59, running: True
I0731 12:12:39.264224  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 60, running: True
I0731 12:12:40.265281  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 61, running: True
I0731 12:12:41.268338  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 62, running: True
I0731 12:12:42.273396  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 63, running: True
I0731 12:12:43.276453  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 64, running: True
I0731 12:12:44.276510  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 65, running: True
I0731 12:12:45.277567  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 66, running: True
I0731 12:12:46.277625  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 67, running: True
I0731 12:12:47.278682  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 68, running: True
I0731 12:12:48.283739  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 69, running: True
I0731 12:12:49.283797  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 70, running: True
I0731 12:12:50.283854  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 71, running: True
I0731 12:12:51.283911  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 72, running: True
I0731 12:12:52.292969  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 73, running: True
I0731 12:12:53.300026  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 74, running: True
I0731 12:12:54.300083  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 75, running: True
I0731 12:12:55.300141  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 76, running: True
I0731 12:12:56.301198  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 77, running: True
I0731 12:12:57.302255  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 78, running: True
I0731 12:12:58.302312  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 79, running: True
I0731 12:12:59.303369  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 80, running: True
I0731 12:13:00.305427  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 81, running: True
I0731 12:13:01.305484  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 82, running: True
I0731 12:13:02.305541  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 83, running: True
I0731 12:13:03.305598  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 84, running: True
I0731 12:13:04.306656  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 85, running: True
I0731 12:13:05.307713  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 86, running: True
I0731 12:13:06.308770  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 87, running: True
I0731 12:13:07.308827  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 88, running: True
I0731 12:13:08.308885  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 89, running: True
I0731 12:13:09.310942  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 90, running: True
I0731 12:13:10.310999  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 91, running: True
I0731 12:13:11.313056  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 92, running: True
I0731 12:13:12.314114  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 93, running: True
I0731 12:13:13.315171  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 94, running: True
I0731 12:13:14.318228  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 95, running: True
I0731 12:13:15.321286  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 96, running: True
I0731 12:13:16.334344  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 97, running: True
I0731 12:13:17.337401  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 98, running: True
I0731 12:13:18.337458  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 99, running: True
I0731 12:13:19.337516  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 100, running: True
I0731 12:13:20.338573  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 101, running: True
I0731 12:13:21.359631  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 102, running: True
I0731 12:13:22.359688  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 103, running: True
I0731 12:13:23.362746  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 104, running: True
I0731 12:13:24.362803  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 105, running: True
I0731 12:13:25.362860  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 106, running: True
I0731 12:13:26.370918  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 107, running: True
I0731 12:13:27.371975  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 108, running: True
I0731 12:13:28.385033  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 109, running: True
I0731 12:13:29.387090  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 110, running: True
I0731 12:13:30.388148  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 111, running: True
I0731 12:13:31.391205  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 112, running: True
I0731 12:13:32.391262  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 113, running: True
I0731 12:13:33.391319  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 114, running: True
I0731 12:13:34.392377  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 115, running: True
I0731 12:13:35.392434  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 116, running: True
I0731 12:13:36.392491  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 117, running: True
I0731 12:13:37.392548  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 118, running: True
I0731 12:13:38.392605  8104 remote_controller.py:163] Connecting to: ws://127.0.0.1:20114/sc2api, attempt: 119, running: True
W0731 12:13:42.524842  8104 sc_process.py:204] Killing the process.
I0731 12:13:42.597846  8104 sc_process.py:182] Shutdown with return code: 1
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pysc2\bin\play.py", line 218, in <module>
    app.run(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pysc2\bin\play.py", line 151, in main
    full_screen=FLAGS.full_screen) as controller:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pysc2\run_configs\platforms.py", line 97, in start
    self, exec_path=exec_path, version=version, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pysc2\lib\sc_process.py", line 116, in __init__
    self._host, self._port, self, timeout_seconds=timeout_seconds)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pysc2\lib\remote_controller.py", line 143, in __init__
    sock = self._connect(host, port, proc, timeout_seconds)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pysc2\lib\stopwatch.py", line 201, in _stopwatch
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pysc2\lib\remote_controller.py", line 174, in _connect
    raise ConnectError("Failed to connect to the SC2 websocket. Is it up?")
pysc2.lib.remote_controller.ConnectError: Failed to connect to the SC2 websocket. Is it up?

is there anyone help me?

**Comment by AthinkingNeal** [comment]
You have to open the Starcraft2 game as well instead of just open the battle net
