### ISSUE TITLE
AttributeError: 'Units' object has no attribute 'noqueue'

### ISSUE THREAD

**Issue by fengmao31** [deepmind/pysc2#292]
when it is in the 0.12，the code is ok.
when it is in the 4.11，the code cannot work.

AttributeError: 'Units' object has no attribute 'noqueue'
ERROR:sc2.main:Error: 'Units' object has no attribute 'noqueue'
ERROR:sc2.main:Resigning due to previous error
--- on_end called ---
Result.Defeat
INFO:root:Result for player 1 - Bot SentdeBot(Protoss): Defeat
![image](https://user-images.githubusercontent.com/19343842/78026369-1ef2cb80-738e-11ea-9082-9dacdfd4d800.png)

**Comment by nortliteborealis** [comment]
I think you mixed up the pysc2 and python-sc2 (from this repo https://github.com/Dentosal/python-sc2) libraries. This is the repository of the library from deepmind pysc2. Your code is not related to it.
