### ISSUE TITLE
"TypeError:has type float, but expected one of: int, long"

### ISSUE THREAD

**Issue by dylink** [deepmind/pysc2#296]
This bug appears when we try to click on a minimap that has the "inverted" coordinates.

This is a type error so it can be corrected by casting the variable into an int.

I can work on it, it's pretty simple, can I do so?

**Comment by dylink** [comment]
I wanted to add that it would be really good for me to work on it because I am a student and I have a work that consists in finding a bug on a freeware/free program and try to correct it.

**Comment by KingKeet** [comment]
That looks like the type of error that is the fault of the person using the package, and it's usually not considered best practice to simply cast something if you can help it.

I'd look at some other repo if you're looking to help out, this one is run by the company DeepMind and as such probably not the type of project that's going to just let you merge something, although I could be wrong, of course.
