### ISSUE TITLE
Tracking In-Game Time

### ISSUE THREAD

**Issue by Natemen96** [deepmind/pysc2#299]
I would like to use the in-game time to make an reward function that decide reward based on how quickly the agent win or loses. Is there an end point to get that time variable? If not, what is the best way of mimicking it? I don't want to just use ```import time; time.time()``` because the simulator is sped up. 

I noticed in the [sc2_env](https://github.com/deepmind/pysc2/blob/master/pysc2/env/sc2_env.py#L116) there's a REALTIME_GAME_LOOP_SECONDS variable but it doesn't seem like it used anywhere so I don't understand it's purpose if it's related to what I'm trying to do.

**Comment by KingKeet** [comment]
The sped-up version of the game runs at 22 fps, so if you need to figure out in-game time you can just take steps and divide by 22 and you'll get time in seconds
