### ISSUE TITLE
Remove Starcraft Fatal Error after run Mac

### ISSUE THREAD

**Issue by tylerwhipple** [deepmind/pysc2#30]
After each agent run, there is a "Unexpected Fatal Error" warning to send feedback to Blizzard. I do not think they will be interested in these errors. Is there anyway to disable them or will this need to be on the starcraft api side?

<img width="662" alt="screen shot 2017-08-13 at 10 32 55 pm" src="https://user-images.githubusercontent.com/1731091/29253215-7b5246e2-8077-11e7-95bf-7e5d72ba2040.png">

**Comment by KevinCalderone** [comment]
I'm not sure why it would be crashing. Can you submit at least one report of that so we can take a look at the logs?

**Comment by tylerwhipple** [comment]
Yes for sure, I just submitted "C6D179D8-1FB0-4467-B533-00C3C9D5210E". Do you want me to put anything in the next error message for you to find it?

**Comment by KevinCalderone** [comment]
No that number should be enough. I'll post here again if I need more info. Thanks!

**Comment by tylerwhipple** [comment]
To be clear, the agent appears to run correctly, and the replay says it saves, it is only after the max steps have completed.

<img width="724" alt="screen shot 2017-08-13 at 11 15 05 pm 1" src="https://user-images.githubusercontent.com/1731091/29253441-4fa38078-807d-11e7-8a65-79cf365d3455.png">

**Comment by stevengritz** [comment]
I've been getting similar crashes after successful replays and agent runs.

**Comment by zsluedem** [comment]
it seems only happened in Mac OSX
