### ISSUE TITLE
Why there is no valid action check in RAW action space?

### ISSUE THREAD

**Issue by Rodnaom** [deepmind/pysc2#310]
If we directly use the `agent.py` entry to start a game using RAW action space, the game will always crash with `KeyError` due to the following lines:

https://github.com/deepmind/pysc2/blob/05b28ef0d85aa5eef811bc49ff4c0cbe496c0adb/pysc2/bin/agent.py#L106

https://github.com/deepmind/pysc2/blob/05b28ef0d85aa5eef811bc49ff4c0cbe496c0adb/pysc2/env/available_actions_printer.py#L34-L37

https://github.com/deepmind/pysc2/blob/05b28ef0d85aa5eef811bc49ff4c0cbe496c0adb/pysc2/lib/features.py#L1520-L1522

So there is no existing way to check availability of actions in RAW action space. Is it designed on purpose? Or just not implemented yet?

BTW, how can I achieve this?

Thx

**Comment by Rodnaom** [comment]
There is `RequestQuery` API in `s2client-proto` but `PySC2` doesn't use it (I searched through codes).

**Comment by tewalds** [comment]
How would you expect to use it from a neural network which takes an observation and immediately returns an action? The valid actions depend on which units to direct the actions to, and that's an arbitrary and potentially large set, to the point that in late game could be any action available to that race. I guess a few would be excluded like researching something that you've already researched, but that wouldn't reduce the available actions by much. We mainly dealt with that by supervised learning where the agent learned the available actions based on what humans did. We don't control individual units, and so the RequestQuery isn't useful.
