### ISSUE TITLE
pysc2 rendering crash on ubuntu 18.04

### ISSUE THREAD

**Issue by samxu1988** [deepmind/pysc2#313]
Hello here,

When I  started to work on pysc2 game environment, I have encountered the following the issue.
$ python3 -m pysc2.bin.play --map Simple64

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
I0730 12:07:32.165569 140136091580224 sc_process.py:135] Launching SC2: /home/hello/StarCraftII/Versions/Base59877/SC2_x64 -listen 127.0.0.1 -port 17730 -dataDir /home/hello/StarCraftII/ -tempDir /tmp/sc-pwcmbv3s/ -eglpath libEGL.so
I0730 12:07:32.169494 140136091580224 remote_controller.py:167] Connecting to: ws://127.0.0.1:17730/sc2api, attempt: 0, running: True
Version: B59877 (SC2.4.0)
Build: Nov 27 2017 21:52:46
Command Line: '"/home/hello/StarCraftII/Versions/Base59877/SC2_x64" -listen 127.0.0.1 -port 17730 -dataDir /home/hello/StarCraftII/ -tempDir /tmp/sc-pwcmbv3s/ -eglpath libEGL.so'
Starting up...
Startup Phase 1 complete
I0730 12:07:33.173148 140136091580224 remote_controller.py:167] Connecting to: ws://127.0.0.1:17730/sc2api, attempt: 1, running: True
Startup Phase 2 complete
Attempting to initialize EGL from file libEGL.so ...
Successfully loaded EGL library!
Successfully initialized display on device idx: 0, EGL version: 1.5

Running CGLSimpleDevice::HALInit...
Calling glGetString: 0x7f5d323e8fe0
Version: 4.6.0 NVIDIA 440.100
Vendor: NVIDIA Corporation
Renderer: GeForce RTX 2080 Ti/PCIe/SSE2
OpenGL initialized!
Listening on: 127.0.0.1:17730 (17730)
Startup Phase 3 complete. Ready for commands.
I0730 12:07:34.175502 140136091580224 remote_controller.py:167] Connecting to: ws://127.0.0.1:17730/sc2api, attempt: 2, running: True
Requesting to join a single player game
Configuring interface options
Configure: raw interface enabled
Configure: feature layer interface enabled
Configure: score interface enabled
Configure: render interface enabled
Entering load game phase.
Launching next game.
Next launch phase started: 2
Next launch phase started: 3
Next launch phase started: 4
Next launch phase started: 5
Next launch phase started: 6
Next launch phase started: 7
Next launch phase started: 8
Game has started.
Updated EGL surface size to 384, 192

Sending ResponseJoinGame
Exception in thread Renderer:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hello/.local/lib/python3.6/site-packages/pysc2/lib/renderer_human.py", line 1706, in render_thread
    self.render_obs(obs)
  File "/home/hello/.local/lib/python3.6/site-packages/pysc2/lib/renderer_human.py", line 69, in _with_lock
    return func(*args, **kwargs)
  File "/home/hello/.local/lib/python3.6/site-packages/pysc2/lib/stopwatch.py", line 212, in _stopwatch
    return func(*args, **kwargs)
  File "/home/hello/.local/lib/python3.6/site-packages/pysc2/lib/renderer_human.py", line 1724, in render_obs
    surf.draw(surf)
  File "/home/hello/.local/lib/python3.6/site-packages/pysc2/lib/renderer_human.py", line 658, in <lambda>
    lambda surf: self.draw_raw_layer(surf, from_obs, name, color))
  File "/home/hello/.local/lib/python3.6/site-packages/pysc2/lib/stopwatch.py", line 212, in _stopwatch
    return func(*args, **kwargs)
  File "/home/hello/.local/lib/python3.6/site-packages/pysc2/lib/renderer_human.py", line 1668, in draw_raw_layer
    surf.blit_np_array(color[layer])
IndexError: index 255 is out of bounds for axis 0 with size 2
I tried to  find a solution, but nothing works till now. Any help or fix would be much appreciated.

Regards,

**Comment by 4ever-Rain** [comment]
I get the same error with you when I use the StarCraftII V4.6.2.
Then I redownload the SC2 V4.10 (Latest version), the error can be solved.
The error maybe caused by a version mismatch. 
I think pysc2(3.0.0) and SC2 V4.10 can work.
