### ISSUE TITLE
connect to existing server

### ISSUE THREAD

**Issue by DrRibosome** [deepmind/pysc2#33]
I think it would be reasonable to allow connecting to an existing server. For example, the cli args could take a host/port to connect to, instead of starting a new server process. This is particularly useful if the sc2 server is running on a remote host

**Comment by zsluedem** [comment]
It is possible, the agent use websocket to connect the game

**Comment by tewalds** [comment]
Why would you want the SC2 instance to run on a remote host? Why not run it locally?

**Comment by Brennan-VanderLaan** [comment]
The only reason I can think of in my case is that running the instance remotely frees up more of my vram on my graphics card for ML tasks. You could also get into some fun (but probably silly) clustering for your bot to talk to the client at that point. I don't see any harm in being able to connect to a remote client.

**Comment by dmyers** [comment]
The game itself is quite large (30gb), so offloading that would be a nice benefit too.

**Comment by InTheCloudDan** [comment]
I'm trying to run SC2 in a docker container and it's exposes the API via a port. So this would make it possible to connect.

**Comment by chris-chris** [comment]
Yeah, I want the remote connection too.
