### ISSUE TITLE
pysc2.lib.protocol.ProtocolError: `actions` called while in state: Status.ended, valid: (Status.in_game)

### ISSUE THREAD

**Issue by Bonstop** [deepmind/pysc2#346]
Sorry if this is a basic issue that I'm failing to understand.
When I ran SMAC on Windows 10 PC, it raise this error:
> raceback (most recent calls WITHOUT Sacred internals):
>   File "D:\software\miniconda\envs\marl\lib\site-packages\smac\env\starcraft2\starcraft2.py", line 420, in step
>     self._controller.actions(req_actions)
>   File "D:\software\miniconda\envs\marl\lib\site-packages\pysc2\lib\remote_controller.py", line 85, in _skip_status
>     return func(self, *args, **kwargs)
>   File "D:\software\miniconda\envs\marl\lib\site-packages\pysc2\lib\remote_controller.py", line 99, in _valid_status
>     func.__name__, self.status, ",".join(map(str, valid))))
> pysc2.lib.protocol.ProtocolError: `actions` called while in state: Status.ended, valid: (Status.in_game)

Can anybody help me or meet this problem in the past?

**Comment by tewalds** [comment]
You're not in a game when you tried to make an action. Most likely the previous game ended.
