### ISSUE TITLE
Is there a way to add agents written in C++ using the official SC2 API?

### ISSUE THREAD

**Issue by slavabez** [deepmind/pysc2#36]
I only have a Linux machine available at the moment, and I'd like to watch some AI I created using the [official API](https://github.com/Blizzard/s2client-api).

For example:

I wrote a bot similar to [this](https://github.com/Blizzard/s2client-api/blob/master/examples/bot_simple.cc) and would like to use pysc2 to spectate it fight a simple computer. As far as I know this isn't possible, but please correct me if I'm wrong.

**Comment by KevinCalderone** [comment]
One option would be to save a replay of the bot, and they play that back in PySC2.

Something like this:
virtual void OnGameEnd() final {
   Control()->SaveReplay(filePath)
}

**Comment by slavabez** [comment]
I've been looking on how to do that, it hasn't been documented yet. Thanks a bunch!
