### ISSUE TITLE
RGB Pixel Values Question

### ISSUE THREAD

**Issue by Eric-Wallace** [deepmind/pysc2#37]
Since the feature of having raw RGB pixels is not available, is it safe to assume the results created in the initial DeepMind paper were all done using the convolutional layers directly on the features such as _unit_density_ and _height_map_? I am struggling to understand how the bot is trained. The observation data seems strange.

**Comment by tewalds** [comment]
Yes, they were trained using the observations you get from SC2Env, which means the feature layers in numpy/tensor form, and the other non-spatial data. We then saved replays regularly, and replayed those on windows to record the videos. For the supervised agents we did a map-reduce over the replays, passing the observations through features.Features.transform_obs to get the same observations as an RL agent and trained on that.
