### ISSUE TITLE
Change the size of the display window?

### ISSUE THREAD

**Issue by KMontag42** [deepmind/pysc2#40]
Hey hey, Linux user here.

Currently when I run the environment, my window is a bit wonky. I have multiple monitors and use i3, so my setup is non-standard to say the least.

I was wondering if there are any flags hidden away that I can use to define the size of the actual environment display window? (not the resolution of the feature layers themselves ^_^)

Any tips would be most appreciated!

Thanks!!

**Comment by tewalds** [comment]
Right now the logic isn't flexible enough to handle arbitrary window sizes. It is computed here: https://github.com/deepmind/pysc2/blob/master/pysc2/lib/renderer_human.py#L255 . Feel free to improve the logic and send a pull request.

**Comment by KMontag42** [comment]
awesome thanks guys! glad to know you are open to PRs, I have a few other tweaks locally I can send.

**Comment by cole-maclean** [comment]
I've ended up just manually changing the scaling constant here:
https://github.com/deepmind/pysc2/blob/master/pysc2/lib/renderer_human.py#L139

Works well for my  purposes, not sure if it's too hacky for a PR or where the best place to put this as a config parameter if you were to take that path, but hopefully this note helps others with the same issue.

**Comment by tewalds** [comment]
What scaling constant did you find more useful? Is this something that could be reasonably be generalized?
