### ISSUE TITLE
problem with subprocess.Popen in sc_process.py

### ISSUE THREAD

**Issue by phraust1612** [deepmind/pysc2#41]
Hi,
Firstly, I'd like to apologize if I'm annoying you because of too much opening issues.
But I'm in trouble with subprocess.Popen in sc_process.py

When I repeat to create and close SC2Env,
OSError occurs after a couple of iterations.
My codes looks like below.

```shell
for episode in range(start_epi, num_episodes):
    with sc2_env.SC2Env(
            "Odyssey",
            agent_race=myrace,
            bot_race=botrace,
            difficulty="1",
            visualize=visualize) as env:
        agent = minerva_agent.MinervaAgent(mainDQN)
        run_result = run_loop( blabla~~)
        env.close()
```
and full error codes are like below
```shell
ERROR:root:Failed to launch
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pysc2/lib/sc_process.py", line 119, in _launch
    return subprocess.Popen(args, cwd=run_config.cwd, env=run_config.env)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1490, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
```

I'm currently using Ubuntu Linux
and I tried to increase my swap memory, but it only helps to increase only one more iteration.
I checked whether subprocess was killed or not (via psutil), but I guess env.close() works well.
If you need to check my full code, [here](https://github.com/phraust1612/MinervaSc2/blob/master/trainingRL.py) it is.

Thank you.

**Comment by tewalds** [comment]
I'm not sure what's wrong there. Can you verify that the game is being shut down properly and that you don't have a bunch still running in the background?

Btw given that you're using SC2Env in a context manager (ie with) you don't need to call env.close explicitly.

Also, it's a good idea to compute the number of actions from len(pysc2.lib.actions.FUNCTIONS) since new abilities may be added in future versions of the game.

**Comment by phraust1612** [comment]
@tewalds yes it's sure that starcraft was shut down after each iteration and none of the process remained running. So it is possible to run the code again after it exits, but only few repetitions similarly. And thank you for your last advice.

**Comment by phraust1612** [comment]
closing this issue due to get solved

**Comment by TimeBreaker** [comment]
@phraust1612  Hi, I am also having an `OSError: [Errno 12] Cannot allocate memory` issue. Could you please tell me how you solved this problem? Thanks a lot.

**Comment by SeanKski** [comment]
Hi there, I'm also running into this problem! Any insights? @phraust1612 , @TimeBreaker
