### ISSUE TITLE
Where can I find all the agents from pysc2

### ISSUE THREAD

**Issue by hexunshi** [deepmind/pysc2#43]
In the sc2le.pdf:
DeepMind:
- PySC2: https://github.com/deepmind/pysc2
- All the agents and experiments in the paper
But I can't find the agents about supervised learning from replays

**Comment by tewalds** [comment]
Unfortunately we haven't released any of the agents trained for the paper. They use internal libraries and are hard to open source.

pysc2/bin/replay_actions.py is an example of how to collect stats from a large number of replays, so you could modify that to generate the specific dataset you care about.
pysc2/agents/ has some trivial example agents for how to interact with the environment. Take a look at #34 for people working on an a3c agent.

**Comment by hexunshi** [comment]
OK,Thank you!
