### ISSUE TITLE
[Help] - Installing

### ISSUE THREAD

**Issue by azshalasa** [deepmind/pysc2#49]
i'm not sure what i'm doing wrong i'm starting  with Phyton/SC2 Deep learning now. I have any idea how it works because i know #C but i'm getting  this error while trying to run something.

C:\Users\Mateus Cordova\Desktop\SC2-DEEPMIND\pysc2-master>python -m pysc2.bin.map_list
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "C:\Python27\lib\runpy.py", line 102, in _get_module_details
    loader = get_loader(mod_name)
  File "C:\Python27\lib\pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "C:\Python27\lib\pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "C:\Python27\lib\pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "pysc2\__init__.py", line 14
    python -m pysc2.bin.map_list.py
                  ^
SyntaxError: invalid syntax

Some one could help me ?

**Comment by tewalds** [comment]
I'm not sure what's wrong there. The command line looks right, but the error suggests you're using ".py" as the ending on the command line. It should be "python -m pysc2.bin.map_list" not "python -m pysc2.bin.map_list.py".

**Comment by azshalasa** [comment]
Tx for fast reply, i've changed to .py just to check if that was the problem. But it keeps the mensage. 
i'm using python-2.7.13 , should i use another one ?  i'm on windows machine. 
I'm not sure if i've installed all things needed. Any idea what coul be missing ?

**Comment by tewalds** [comment]
Python 2.7.13 should work fine. Others have said it works on Windows. Can you take a look at what's in the file (.../__init__.py) it thinks has the syntax error? It should be empty other than copyright notice. It looks like you've got something weird in there.

**Comment by azshalasa** [comment]
I did not modify any file, just have downloaded and tryed to execute. 
![Uploading Sem título.jpg…]()

**Comment by tewalds** [comment]
I don't know how that line got there, but it's definitely not in the source: https://github.com/deepmind/pysc2/blob/master/pysc2/__init__.py . I suggest removing it and trying again.

**Comment by azshalasa** [comment]
Tx alot! I dont know how that got there too, just unzinp and run. But you solve it, tx alot! 
Let's start the games and learning before teaching the I.A xD 

You can close this topic now. ;)
