### ISSUE TITLE
Missing Observations

### ISSUE THREAD

**Issue by skjb** [deepmind/pysc2#52]
Could we add some of the following details to the observations? These details are visible to a human player on the loading screen:

1. The map (name, version, anything required to get a unique ID in case the maps change over time)
2. Map spawn locations (although maybe this could be included in the map details in point 1)
3. Each player's chosen race (T, V, Z, random) - not the actual race for random

Since a player's strategy will often depend on the map, the opponent's race and their location, all of these details would help a bot in the early game.

A more advanced bot may study the feature layers, but simpler bots could achieve a lot with less effort if these details were available.

**Comment by tewalds** [comment]
Also add:
- Alerts when units/buildings have been attacked
- Feedback when actions cannot be performed, e.g. cannot place building

**Comment by skjb** [comment]
- Base/gas worker counts (e.g. 12/16 or 2/3)

**Comment by moon920110** [comment]
Is there any method to get some signals when I failed to place building?

**Comment by moon920110** [comment]
Well, I think I found the way to know the failure of placing building.

when the "env.step(actions=[actions.FunctionCall(_BUILD_SUPPLY_DEPOT, [_SCREEN], [incices]])])" command is working, the minerals are immediately decreased. But if the command is fail(caused by some reasons), then the minerals are not decreased.

I think we can used this principle.

**Comment by skjb** [comment]
- AI surrender (also need an action to accept)

**Comment by liuruoze** [comment]
Yes. I think all of these will help to improve the bot. Especially when the opponent AI says 'gg'， there should be a way for our agent to notice that and accept it to make this game close fast which makes training more fast.

**Comment by tewalds** [comment]
Added errors and alerts here: 1f1c447 . Unfortunately the API doesn't actually return many of them.

**Comment by SebastianBelkner** [comment]
- Base/gas  worker counts (e.g. 12/16 or 2/3) as requests by @skjb has been solved some time ago. you can access it via obs.observation.feature_unit.assigned_harvesters = 23 and  ideal_harvesters = 24
