### ISSUE TITLE
the problem of maps:reading map errors

### ISSUE THREAD

**Issue by PearlZF** [deepmind/pysc2#54]
I put the map packages into StarCraft II/Maps, but still show: "ERROR:root:Error reading map 'Simple64' from: /Applications/StarCraft II/Maps/Melee/Simple64.SC2Map"

**Comment by tylerwhipple** [comment]
What OS? Im guessing Mac?

**Comment by PearlZF** [comment]
Yes, it's mac

**Comment by tylerwhipple** [comment]
wait, did you put the whole melee/* into the maps folder or just the simple64?

**Comment by tylerwhipple** [comment]
if you type `open /Applications/Starcraft\ II/Maps` into your terminal do you see the Melee/Simple64.SC2Map ?

**Comment by PearlZF** [comment]
I put the whole melee/* into the maps folder, after the type  I can see Melee/Simple64.SC2Maps and others

**Comment by tewalds** [comment]
Make sure the map is where the error says it should be.
