### ISSUE TITLE
Edit existing and add new mini-maps

### ISSUE THREAD

**Issue by arcanefoam** [deepmind/pysc2#59]
It would be appreciated if we could also get a small guide on how to edit the existing or create new mini-maps for training purposes. I have searched a lot but still can't figure out how to edit or create .sc2map files; the Star Craft map editor can only read/create .scm and .scx files.

**Comment by KevinCalderone** [comment]
There are a bunch of docs here: http://s2editor-tutorials.readthedocs.io/en/master/

You should be able to just open and edit the existing mini-game maps. I agree it would be nice if we also had documentation specific to how to make/edit mini-game maps.

**Comment by arcanefoam** [comment]
Thanks! Interestingly enough my game does not look like any of the
screenshots on that guide, perhaps I downloaded the wrong version. Probably
the case, as my StarCraft editor does nor recognize .sc2map files.

I'll try to download SC2 again, see if this helps.

As you said, though, it would be nice to have a small guide on how to make
our own mini-maps or edit the existing. For me, the jump from the no fog of
war, no camera movement required mini to a melee or ladder is too big. I
would rather introduce one or the other first, then both, then move to
harder maps.



On 3 Sep 2017 9:13 pm, "Kevin Calderone" <notifications@github.com> wrote:

There are a bunch of docs here: http://s2editor-tutorials.
readthedocs.io/en/master/

You should be able to just open and edit the existing mini-game maps. I
agree it would be nice if we also had documentation specific to how to
make/edit mini-game maps.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/deepmind/pysc2/issues/59#issuecomment-326828363>, or mute
the thread

**Comment by KevinCalderone** [comment]
The editor comes with the regular game installation.

In the Blizzard Launcher, there is a "Launch Editor" button near the top of the SC2 page.

You can also launch it directory. Here is where to find it on Windows:
C:\Program Files (x86)\StarCraft II\StarCraft II Editor.exe

**Comment by lschmelzeisen** [comment]
There also exists a community maintained guide creating mini-games: https://github.com/SoyGema/Startcraft_pysc2_minigames (not mine)

**Comment by ConstantinosM** [comment]
I experience problems when trying to open a map from SC2 Map Editor. It asks me for a Swarm License. All maps when I am trying to open them from the Editor are not available for opening (the file name color is faded). I am using Mac Sierra. Is there any workaround solution for these licenses?
