### ISSUE TITLE
Observation feature for unit list.

### ISSUE THREAD

**Issue by chris-chris** [deepmind/pysc2#60]
1) Is there a plan for unit list observation feature?

I could find the list of units in raw API data from StarCraft II.
env._obs.observation.raw_data.units
<img width="1106" alt="2017-09-03 9 30 13" src="https://user-images.githubusercontent.com/3013964/30002886-21e13e00-90ef-11e7-8a1b-eb21ee67420f.png">

But I can not find the unit list in observation space.

2) How can I retrieve unit_id for 'select_unit_id' action?

select_unit_id=ArgumentType.scalar(500),

I could not find unit_id from raw_data from StarCraft II
env._obs.observation.raw_data.units

Thanks!

**Comment by KevinCalderone** [comment]
For the second question:

The 'select_unit_id' action is the equivalent of having multiple units selected, and clicking on one of the unit icons on the bottom of the screen. In this UI you don't have the information of exactly which on screen unit the icons correspond to. For this reason, the information of those units is exposed separately in Observation::ui_data::multi::units. The 'unit_index' of the action corresponds to the index into this units array.

**Comment by chris-chris** [comment]
@KevinCalderone Oh, much thanks!!!!

**Comment by tewalds** [comment]
More concretely it's the index into the multi_select observation.
