### ISSUE TITLE
DefeatZerglingsAndBanelings mini-game sometimes get stuck

### ISSUE THREAD

**Issue by Seraphli** [deepmind/pysc2#65]
This game will get stuck after eliminate all enemies. Sometimes it wouldn't generate new enemies after several runs. I encountered this problem when I was playing it on the windows.

**Comment by KevinCalderone** [comment]
Do you have a replay of the game when this occurs? That may help us debug it.

By default it should be saving them here:
C:\Users\username\Documents\StarCraft II\Replays\Multiplayer

**Comment by Seraphli** [comment]
https://www.dropbox.com/s/v33zxcz8bq8v4we/CombatFocus%20%286%29.SC2Replay?dl=0
Here is the replay file.

**Comment by KevinCalderone** [comment]
Thanks for the replay. That made it easy to debug.

There is a bug in the map with how it is detecting all the zerglings/banelines being dead. This can cause no new enemies to spawn and you have to just wait for the timer to run out. I'll see if I can update the maps.

Your replay also shows that when the timer hits 0, the game still gets stuck and doesn't start another run. Are you seeing PySC2 getting stuck when this happens? From the replay it looks like everything is behaving properly, so there may be a second bug in PySC2. I'll need repro steps to be able to debug that.

What command line are you using to run this? The library doesn't seem to come with a scripted agent for this map.

**Comment by Seraphli** [comment]
Thank you for fixing this bug. About the command line, I think you don't need any command line parameter to play them. I just follow these steps in this [video](https://www.youtube.com/watch?v=AltjnZfM12I).

While you playing the mini-game yourself, you have to type `reset` command to reset current game. I think PySC2 works fine because there is a ['reset'](https://github.com/deepmind/pysc2/blob/cad5a011492372abf484bd7a8cc69e7ed24b8d8c/pysc2/env/sc2_env.py#L206-L218) function of the environment. As soon as the flag 'done' is true, you can reset the environment by yourself, just like [this](https://github.com/chris-chris/pysc2-examples/blob/49514647242ac2d10cf45bba214f6065a0aa4323/deepq_mineral_shards.py#L381-L382).

I just notice that there is a [mechanism](https://github.com/deepmind/pysc2/blob/cad5a011492372abf484bd7a8cc69e7ed24b8d8c/pysc2/env/sc2_env.py#L223-L224) that will automatically reset the environment. I guess people still use manual reset because the API is kind of like OpenAI gym. We don't realize there is a such mechanism.

**Comment by KevinCalderone** [comment]
Ah ok so it sounds like there is no second issue then. I'll just look into getting the map updated then.

**Comment by Seraphli** [comment]
:smiley:
