### ISSUE TITLE
DefeatRoaches agent.pysc2.scripted_agent.DefeatRoaches error 

### ISSUE THREAD

**Issue by SoyGema** [deepmind/pysc2#67]
Hi There!
I am working in a tutorial for  first understanding of mini games in order to help to create more of them 
[tutorial minigame](https://github.com/SoyGema/Startcraft/blob/master/README.md)

I do have a problem with scripted_agent as it runs but always crushes 
`python3 -m pysc2.bin.agent --map DefeatRoaches --agent pysc2.agents.scripted_agent.DefeatRoaches`

NSWindowEdgeResizing is off!
2017-09-08 16:21:50.709 Python[3397:240836] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/t8/zmf1s_857zgdxycxnrk_g8080000gn/T/org.python.python.savedState
   0/no_op                                              ()
   1/move_camera                                        (1/minimap [64, 64])
   2/select_point                                       (6/select_point_act [4]; 0/screen [84, 84])
   3/select_rect                                        (7/select_add [2]; 0/screen [84, 84]; 2/screen2 [84, 84])
   4/select_control_group                               (4/control_group_act [5]; 5/control_group_id [10])
   5/select_unit                                        (8/select_unit_act [4]; 9/select_unit_id [500])
 453/Stop_quick                                         (3/queued [2])
   7/select_army                                        (7/select_add [2])
 451/Smart_screen                                       (3/queued [2]; 0/screen [84, 84])
 452/Smart_minimap                                      (3/queued [2]; 1/minimap [64, 64])
 331/Move_screen                                        (3/queued [2]; 0/screen [84, 84])
 332/Move_minimap                                       (3/queued [2]; 1/minimap [64, 64])
 333/Patrol_screen                                      (3/queued [2]; 0/screen [84, 84])
 334/Patrol_minimap                                     (3/queued [2]; 1/minimap [64, 64])
  12/Attack_screen                                      (3/queued [2]; 0/screen [84, 84])
  13/Attack_minimap                                     (3/queued [2]; 1/minimap [64, 64])
 274/HoldPosition_quick                                 (3/queued [2])
Took 67.693 seconds for 2500 steps: 36.932 fps
Wrote replay to: /Applications/StarCraft II/Replays/DefeatRoaches/DefeatRoaches_2017-09-08-14-22-58.SC2Replay
WARNING:root:Terminating attempt 0...
WARNING:root:Terminating attempt 1...
WARNING:root:Terminated.
MacBook-Air:~ me$ 2017-09-08 16:23:43.703 Blizzard Error[3429:241911] Blizzard Error Report ID: 3CC2DD1F-A38E-471B-8911-F497BBB532FC

[replay ](https://github.com/SoyGema/Startcraft/tree/master/Replays)
Thanks for all the help !

**Comment by KevinCalderone** [comment]
From looking at that error report, it appears to be the same issue as this:
https://github.com/deepmind/pysc2/issues/30

I had suggested a workaround to DeepMind but it looks like they haven't implemented it yet. I will poke them again about it.
