### ISSUE TITLE
SC2Map Programmatic Generation

### ISSUE THREAD

**Issue by jozhang97** [deepmind/pysc2#68]
I am familiar with the .SC2Map creation using the StarCraft II Editor UI. 

Is there any way of creating a .SC2Map file programmatically, given the state of a game? Perhaps some sort of MPQ encoder? 

Thanks in advance.

Edit: Also, Is it possible to fetch SC2Map data from a Replay file? (My assumption is that the replay file must have all the information to load a game, thus it must have the map data)

**Comment by KevinCalderone** [comment]
There is no tools that I know of for editing SC2Map files outside of the editor. What are you trying to do?

For programmatic generation, the direction we have been thinking about is to have a completely empty map, and they use protocol requests to populate the map (eg. RequestDebug::DebugCreateUnit).

In the protocol, there is a RequestReplayInfo query to get the map information. Replays only contain the file path to the map. Playing back a replay assumes you already have the correct map data on your system. We have discussed possibly adding an option to store the map data in the replay itself.

**Comment by jozhang97** [comment]
I am trying to start playing a game (either as a human or as an agent) in the middle of a replay. My first thought was to store the information into a .SC2Map file while rendering the replay and run the game with that new map file. Alternatively, quick_save and quick_load looked feasible but is not yet ready. Would there be any better ways of doing this?

**Comment by KevinCalderone** [comment]
I can't think of a good way of doing that right now.

The current plan for quick_save/quick_load is for it to just work within the same game session. We could potentially add a full_save/full_load that would let you start a new game using a save, but that currently isn't planned.

**Comment by jozhang97** [comment]
Ahhh I see. Thank you for your help!
