### ISSUE TITLE
some problems about entropy regularization

### ISSUE THREAD

**Issue by XHUJOY** [deepmind/pysc2#69]
There is a simple implementation of DeepMind's PySC2 RL agents and I have shared it on https://github.com/XHUJOY/pysc2-agents

When use entropy regularization, I can't get reasonable results. I have some problems about entropy regularization. Firstly, in the following formulation
![entropy](https://user-images.githubusercontent.com/15272722/30261983-9f3befa4-9701-11e7-986d-2e45fd7fd5f7.JPG)
should the 3rd term be computed gradient? Second, in the implementation, should i add the entropy regularizations of spatial actions and non-spatial actions separately or not?

**Comment by OriolVinyals** [comment]
The third term induces a gradient over the parameters of the policy (if that's what you are asking). We so far have added all the entropy losses of all the actions types / from all softmaxes (spatial and non-spatial).
