### ISSUE TITLE
SyntaxError in Python 3

### ISSUE THREAD

**Issue by cclauss** [deepmind/pysc2#7]
flake8 testing of https://github.com/deepmind/pysc2 on Python 3.6.2

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./pysc2/bin/gen_actions.py:143:50: E999 SyntaxError: invalid syntax
    if ability.target in (sc_data.AbilityData.None,
                                                 ^
```

**Comment by tewalds** [comment]
Fixed in 43a23ed
