### ISSUE TITLE
Remote environment with Windows Server 2012.

### ISSUE THREAD

**Issue by a3626a** [deepmind/pysc2#72]
I tried to run 
"python -m pysc2.bin.agent --map Simple64"
using Remote Desktop. (local: Windows 10, remote: Windows 2012)

However it failed with the message 
"Running Starcraft II Through a Remote Desktop Connection is Not Supported. Exiting Program."
which seems like same : http://www.blizzhackers.cc/viewtopic.php?f=220&t=487510

To work around this, it tried to connected remote server using Power Shell with command "Enter_PSSession"
Executing "python -m pysc2.bin.agent --map Simple64" with remote session create Starcraft 2 process, and soon Blizzard_Error process, which seems like the same as the case above.

Is there any method to solve this problem, or work around this?

**Comment by KevinCalderone** [comment]
This is not something we currently support. Remote desktop was disabled since there were a bunch of graphical and sound bugs. Would require some research to determine if it is safe to turn back on.

Another option could be to add a headless windows mode. That currently isn't planned either however.

**Comment by a3626a** [comment]
Because I guessed Remote Desktop is disabled by graphical issue, and I also tried `--render false` option.  It did not work, too.

should headless windows mode be supported by SC2 itself? (not pysc2)

**Comment by KevinCalderone** [comment]
The windows SC2 client currently doesn't have a headless mode.
