### ISSUE TITLE
starcraft 3.17 CollectMineralShards map crashes

### ISSUE THREAD

**Issue by ThoMas85** [deepmind/pysc2#76]
Other maps are loading and agents are working. 
Mineralshards mini game worked in previous version.

Running win7 with nvidia GPU

**Comment by KevinCalderone** [comment]
This is the same issue as: deepmind/pysc2#53. The fix will be out soon in the 3.18 patch.

If you want to workaround it in the meantime, you can [revert your install back to the 3.16.1 build](https://github.com/deepmind/pysc2/issues/53#issuecomment-326829857).
