### ISSUE TITLE
Select point won’t work

### ISSUE THREAD

**Issue by doudoujay** [deepmind/pysc2#81]
I tried to use select point instead of select unit.

```python
_SELECT_ALL_OF_TYPE = 2
_UNIT_TYPE_VIEW = features.SCREEN_FEATURES.unit_type.index
def getTerrainBarracksLocation(obs):
    if any(_TERRAN_BARRACKS in sublist for sublist in obs["screen"][_UNIT_TYPE_VIEW]):
        return zip(*np.where(obs["screen"][_UNIT_TYPE_VIEW] == _TERRAN_BARRACKS))
location = getTerrainBarracksLocation(timestep.observation)
point = list(location[0]) #get point from a lot of locations
a = _SELECT_POINT
args = [[_SELECT_ALL_OF_TYPE],point]
a_call = actions.FunctionCall(a, args)
timestep = env.step(actions=[a_call])[0]
```
But, after I step through the a_call, I still can't get the correct selected unit in single_select tensor or multi_select tensor. Any thing went wrong?

**Comment by tewalds** [comment]
This should work, though I think you're swapping x and y. Take a look at https://github.com/deepmind/pysc2/blob/master/pysc2/agents/scripted_agent.py#L45 for how I find the location of a beacon.
