### ISSUE TITLE
Failed to open map archive

### ISSUE THREAD

**Issue by luka-papez** [deepmind/pysc2#83]
I am having problems running replays using the replay_actions.py file.

I have StarCraft build B55958 and the replays work when I use replays from the replay pack you've provided. However, when I try a custom replay I get this error:

https://pastebin.com/XNW8Mgax

The replay is this one (saved to Replays folder):
http://ggtracker.com/matches/7139489
(this is not the only problematic one, I obtained many and none of them work)

Contents of my Maps folder shows that I have map Abyssal Reef LE installed: 
`
ls -1R Maps/
Ladder2017Season1
Ladder2017Season2
Ladder2017Season3
Melee
mini_games
`

./Ladder2017Season1:
**AbyssalReefLE.SC2Map**
BelShirVestigeLE.SC2Map
CactusValleyLE.SC2Map
HonorgroundsLE.SC2Map
NewkirkPrecinctTE.SC2Map
PaladinoTerminalLE.SC2Map
ProximaStationLE.SC2Map

Can I somehow force the map name and manually find the required map file? (since I have this information)

EDIT: it didn't work because I deleted "Cache" folder from the "Battle.net" folder. Now that I've extracted again the replay packs provided by you, the problematic replay on Abyssal Reef works. 

So does the Battle.net folder contain some map/replay information? What if I have a custom map? How to generate this information?

**Comment by KevinCalderone** [comment]
A replay may depend on either a local map or a battlenet published map.

When you play a game locally with the API, you usually use one of your local .SC2Map files.

When you play a game online, it always uses maps that were published to the battlenet service. The game downloads and caches these maps in the Battle.net/Cache folder. These types of maps are a slightly different ".s2ma" file format.

A custom map may require either depending on how you played on it. To play back a replay, you need the same version of the map that the game was played on. If you made a custom map with the editor and played a game using the .SC2Map file, then you just need that .SC2Map file to watch the replay. However if you made a custom map, published it to battlenet, and then played a game on it online, then you will need a Battle.Net/Cache folder containing that map to watch that replay.

If you've played the replay manually in the game client, it the require map should be in the Battle.Net/Cache folder. There is also a command line too built into the game to generate the cache for a set of replays:
[https://github.com/Blizzard/s2client-proto/issues/12#issuecomment-321687678](https://github.com/Blizzard/s2client-proto/issues/12#issuecomment-321687678)

**Comment by tewalds** [comment]
If you run replay_info on the replay it'll tell you the expected map path. If there is no map_path, then it expects to find the map in the battle.net cache.
