### ISSUE TITLE
Does the API enable running agent vs agent simulations?

### ISSUE THREAD

**Issue by LordAddy** [deepmind/pysc2#84]
Does the API enable running agent vs agent simulations?

I would like to use the PySC2 API in my master thesis, and the idea is to use Deep RL on an agent that is going to be fighting against another instance of itself. So is it possible to have 2 running instances of the feature layer api, one for each agent/player?

Initially, I assumed that this functionality is there because it seems like a quite logical feature of such a framework. However, after reading the accompanying paper on arxiv, the last sentence of its conclusion is suggesting otherwise, that self-play is a feature _to come_.

**Comment by tewalds** [comment]
No, it's something we're planning to get working and release, but it's not ready yet.

**Comment by LordAddy** [comment]
Is there an expected timeline? 3 months? 6 months? A year? Or no idea at all?
