### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Random'

### ISSUE THREAD

**Issue by keerthanpg** [deepmind/pysc2#86]
After following the installation steps, when i ran `python -m pysc2.bin.agent --map Simple64`, it reported an error 

> File "/home/keerthana/.local/lib/python2.7/site-packages/pysc2/env/sc2_env.py", line 43, in <module>
    "R": sc_pb.Random,
AttributeError: 'module' object has no attribute 'Random'

Why is this happening? I was using StarCraft 3.16.1

**Comment by keerthanpg** [comment]
Figured out the problem. This happens when you use Python 2.7 and either of StarCraft 3.17 or 3.16.1. I switched to Python 3.5 and it quickly started working!

**Comment by wing3s** [comment]
If you want to continue to use Python 2.7.x, follow this pull request can also make it work. [https://github.com/deepmind/pysc2/pull/85](https://github.com/deepmind/pysc2/pull/85)

**Comment by tewalds** [comment]
This should be fixed in e9d1293 and 39f84b0.
