### ISSUE TITLE
Where could I download Battle.net Cache?

### ISSUE THREAD

**Issue by wuhuikai** [deepmind/pysc2#9]
I downloaded 3.16.1 - Pack 1.zip and unzip it, but only found replay files. Where could I download all the maps from Battle.net Cache used for replays?  Thank you !

**Comment by JustinMBrown** [comment]
I found a work around. I was getting a cache error when trying to watch  a replay using: python -m pysc2.bin.play --replay <path-to-replay>

To fix it, just load the replay you want to view in the actual SC2 game, and the cache will be built. Then, when you run your command, it will find the cache successfully. It's a pain, but it should be enough to get you going. And there aren't too many maps, so if you can find a replay from each map and load it using the game, you're good to go.

**Comment by KevinCalderone** [comment]
I answered this in issue #12 of the s2client-proto repo. We made a mistake when uploading the replay pack where we forgot to include the Battle.net cache.

**Comment by wuhuikai** [comment]
Since #12 solved this problem, I closed this issue. Please refer to #12 for details.

**Comment by wuhuikai** [comment]
deepmind/pysc2/issues/9 resolved this problem, so I closed this issue.
