### ISSUE TITLE
How is the time limit defined for mini games?

### ISSUE THREAD

**Issue by gblackout** [deepmind/pysc2#90]
Hi there,

(1) I was wondering how are these time limits on seconds (120s, 180s, etc.) defined for the mini games? I found in mini_games.py it sets

game_steps_per_episode=0

which should mean no time limit at all?

(2) Is there a standard conversion between second and frame? Since I found in the ladder map we have 

game_steps_per_episode = 16 * 60 * 30  # 30 minute limit.

Does that mean 1 sec = 16 frames?

Thanks.

**Comment by Xaxetrov** [comment]
Hi,

Yes for mini games, you are running in "normal" speed, so 16 frames per "second" (but your simulation will hopefully run several "game seconds" per "real second") by default.

I don't know for game_steps_per_episode=0 either, the documentation on this API is really lacking...

Good luck with your projects.

**Comment by tewalds** [comment]
For the mini games the time limits are defined in the map file itself, so the comment mentions what is defined in the map but doesn't enforce it from the python side.

For more information about game speed look at https://github.com/deepmind/pysc2/blob/master/docs/environment.md#game-and-action-speed .
