### ISSUE TITLE
Avoid rendering of SC2 client

### ISSUE THREAD

**Issue by Xaxetrov** [deepmind/pysc2#91]
Hi everyone,

I know the option "--norender" to avoid the rendering of feature layers. It works fine.
However, the starcraft 2 client of my computer keeps showing up. That annoys me a lot because it slows the simulation and adds a loading time at launch.

How can one avoid every rendering from happening ?

Thanks a lot.

**Comment by tewalds** [comment]
This is a request for Blizzard since it requires changes to the game itself. Alternatively you can use the linux install which always runs without a UI.

**Comment by Xaxetrov** [comment]
@KevinCalderone an idea ?

**Comment by KevinCalderone** [comment]
A headless mode for WIndows/Mac is not currently planned. Using Linux is your best option if you want the best performance.

Another option would be to run the Linux build on Windows via docker. We've made some progress towards that: https://github.com/Blizzard/s2client-docker

**Comment by JohnSegerstedt** [comment]
Sorry if unrelated; but does anyone here know how much quicker it is to go through an entire replay in headless/no UI-mode than it is with the game rendering?
