### ISSUE TITLE
Can not find Simple64 map

### ISSUE THREAD

**Issue by alexpantyukhin** [deepmind/pysc2#92]
Hi! I have tried the command 'python -m pysc2.bin.agent --map Simple64' But got FileNotFoundError. No such file ot directory. Where I can fond this map? 
OS: Windows 7.

**Comment by LordAddy** [comment]
You can download them here: https://github.com/Blizzard/s2client-proto#downloads

For the minigames, go to the Readme of this project

**Comment by KingKeet** [comment]
The files from the download link are password protected for some reason, is there another place I can download them?

**Comment by Nickrader** [comment]
> The files from the download link are password protected for some reason, is there another place I can download them?

This place is fine.
Review the AI and Machine Learning License first.
`By typing in the password ‘iagreetotheeula’ you agree to be bound by the terms of the AI and Machine Learning License`
