### ISSUE TITLE
pysc2.bin.play: mod or map dependencies...no longer available

### ISSUE THREAD

**Issue by loganjhennessy** [deepmind/pysc2#94]
I am able to run replays from the replay pack just fine using:

`python -m pysc2.bin.play --replay <path/to/replay>`

But when I try to run the same command on a personal replay from a 1v1 ladder match, I get the following error: 

`SC2APIProtocol.ResponseStartReplay.Error.LaunchError: 'The  launch of this game makes reference to mod or map dependencies which are no longer available.'`

Full console dump [here](https://gist.github.com/loganjhennessy/c831cb5428c449d60f9be047bd68e82b).

Some more specifics. I'm running the pysc2 command from an Ubuntu 16.04 VM, the replays were generated on Battle.net using the Windows client.

Things I've eliminated:

- Game version miss-match. This is not it. The version of my personal replay was 3.16.1.55958, and I was able to find and run replays of the same version from the replay pack.
- Missing map. Also not it. I tried several replays with different maps, again I verified I could find and run a replay with the same map from  the replay pack.

So, this leaves two things that I can think of right now.

1. Something about attempting to run a replay generated on Windows via the Linux client. But, if this is the case, then how were the replays in the replay pack generated? Obviously those weren't played on Linux, so did they undergo some kind of preprocessing?
2. A flag that must be set when attempting to run a replay that isn't from the replay pack. This will be my next line of investigation.

I guess I'd just like to know if running replays generated from other systems is possible, and if not then is it even possible using the open-source tools that have been provided?

For context, I'd like to build a strategy analyzer app using supervised learning. To analyze someone's strategy, I'll need to accept their replay regardless of what system it was generated on. If I can't do that, it's a bit of a non-starter.

I'll be posting this to the  [Starcraft II API Forum](https://us.battle.net/forums/en/sc2/22814033/) as well.

Thanks.

**Comment by tewalds** [comment]
My guess is that you don't have the map file for "Interloper LE" in your battle.net cache. You can copy over all the files from your other machine, or just download season 3 here: https://github.com/Blizzard/s2client-proto#downloads .
