### ISSUE TITLE
How is the random agent trained?

### ISSUE THREAD

**Issue by botdot** [deepmind/pysc2#95]
I can not understand where the data about each start is saved
Tell me please

**Comment by tewalds** [comment]
I'm really not sure what you're asking here. The random agent isn't trained; it's random.

**Comment by botdot** [comment]
And then how did you create such an agent?
https://www.youtube.com/watch?v=WEOzide5XFc

**Comment by Eric-Wallace** [comment]
Please read the following paper https://arxiv.org/abs/1708.04782 for information on the trained agent using the A3C algorithm.

**Comment by botdot** [comment]
Where can I get one?

**Comment by Eric-Wallace** [comment]
@botdot You will need to write your own agent or find some available tutorials online. There is a number of resources available if you look in the open/closed issues and/or pull requests. There is also sample code posted online in a number of tutorials if you search on the web.

**Comment by botdot** [comment]
It is strange why the most important part of deeptind deepmind not to show

**Comment by botdot** [comment]
It's terrible to say that you are doing artificial intelligence and in fact you created a normal script

**Comment by Eric-Wallace** [comment]
The random agent script is there just to demonstrate some of the basic functions of the API. It exists so developers can learn how to use the API and start developing their own bots. 

Deepmind is indeed doing artificial intelligence, but the majority of their ML code lives internally inside their company. The agent you see in the youtube video is a reinforcement learning agent trained using an algorithm that Deepmind developed known as Asynchronous Advantage Actor-Critic. I recommend you read the paper I posted above and some of Deepmind's other work to get a feeling of what artificial intelligence they are developing.

**Comment by botdot** [comment]
So why do not they throw off the source code of the agent?

**Comment by tewalds** [comment]
That is much more tied to internal libraries and hardware, and is shared with lots of other internal projects that aren't/can't be open sourced. Hopefully the paper is enough to get you started.
