### ISSUE TITLE
Pysc2 crash due to protocol issue.

### ISSUE THREAD

**Issue by keerthanpg** [deepmind/pysc2#97]
When I run `python -m pysc2.bin.agent --map Simple64` or `python -m pysc2.bin.agent --map CollectMineralShards --agent pysc2.agents.scripted_agent.CollectMineralShards` , pysc2 crashes while saying this:   

>   File "/home/keerthana/.local/lib/python3.5/site-packages/pysc2/lib/protocol.py", line 152, in _read
>     response_str = self._sock.recv()
>   File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "/home/keerthana/.local/lib/python3.5/site-packages/pysc2/lib/protocol.py", line 63, in catch_websocket_connection_errors
>     raise ConnectionError("Connection already closed. SC2 probably crashed. "
> pysc2.lib.protocol.ConnectionError: Connection already closed. SC2 probably crashed. Check the error log.

How do I solve this issue?

**Comment by KevinCalderone** [comment]
Is that the only map it crashes on? It is probably the same issue as: https://github.com/deepmind/pysc2/issues/53

There is a bug in the 3.17 build. You can workaround by running the 3.16.1 build. It will be fixed in the next Linux build.

**Comment by keerthanpg** [comment]
Yeah, random agent on simple64 and human play are running fine.

**Comment by keerthanpg** [comment]
Yes. Worked when I shifted to 3.16. Thanks
