### ISSUE TITLE
Low FPS

### ISSUE THREAD

**Issue by Hjax** [deepmind/pysc2#99]
Hello,

When I run any of the minigames through the editor or through the C++ api, i have smooth framerates. But when I launch the same minigames from pysc2 I experience very low (<20) FPS.
 I am on a high end system (i5 6600K, GTX1070, 16 GB RAM) so my system isn't causing the poor performance. 

This game is slow / stuttery enough that I can not collect any meaningful data on my performance in the minigames.

Thanks,
Kevin Konrad

**Comment by tewalds** [comment]
How are you running it? This might be due to pysc2 going in single step mode, so the game will wait for pysc2 to ask for the next step. This leads to some odd UI rendering bugs. If you're running bin/play, try with --realtime to see if that fixes it.
